### ISSUE TITLE
Add correctness tests

### ISSUE THREAD

**Issue by odd** [scala/collection-strawman#103]
A way of automatically verifying correctness of the implemented collections would be nice to have in addition to the benchmarking suite (especially during the optimization phase). 

Two existing code bases to look at are: 
https://github.com/scala/scala/tree/2.13.x/test/junit/scala/collection
https://github.com/scala/scala-collections-laws

**Comment by julienrf** [comment]
This issue has been partially fixed: unit tests have been ported to the strawman. Property-based tests are being ported.
