### ISSUE TITLE
Collections meeting 06/27

### ISSUE THREAD

**Issue by szeiger** [scala/collection-strawman#118]
Topics for the next meeting, feel free to add more:

- Should we provide buffering transformations on Iterator (as implemented in #96) or only on Iterable (as in the 2.12 collections)?
- Empty parameter list vs no parameter list? We should make a decision based on the direction Dotty will take. Also consider Java interop.
- Implicit builders #112 vs #114.
- Type inference issue for `collect` (see #117)
- Merge `Vector` (#115)
- Merge `Traversable` and `Iterable` operations (#119 and #120)
- Runtime error with Dotty only in #48
- Non-laziness of `#::`

**Comment by szeiger** [comment]
Meeting summary:
- Use #114 and defer type-driven building to a later time. Investigate Dotty build problem (@szeiger)
- Merge #115, add `StrictOptimizedSeqOps` (@julienrf)
- Non-laziness of right-associative operators: Don't have such operators until we can fix the underlying problem
- Only add methods like `dropRight` to Iterable, not Iterator (same as Scala 2.12 collections)
- Defer decision about empty parameter lists

**Comment by Ichoran** [comment]
That all sounds good.

**Comment by julienrf** [comment]
I’m closing this issue because we have created separated issues for each actionable thing.
