### ISSUE TITLE
Add `MultiSet`

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#133]
And maybe `MultiMap`?

**Comment by Ichoran** [comment]
Counted, or with contents? They're very different.

**Comment by julienrf** [comment]
Intuitively I would say “counted”. I’m not sure to see the point of having multiple equal elements.

**Comment by Ichoran** [comment]
Counted sets are more like Scala's existing sets, where you can't actually (in general) get back the exact copy you put in, just test for equality.  If the set structure is just organizational, and the elements might possibly have different contents, then a MultiSet that hangs on to the different elements is basically the output of `groupBy`.

**Comment by ShaneDelmore** [comment]
For me the canonical example is that it would be nice to have a great data structure to use when people want to count things.  Want to count frequency of characters in a string, slam them all into a char MultiSet.  I have also heard them called histograms if that makes it more clear that it is for counting items, not generic grouping of items.

**Comment by odersky** [comment]
For simulating counted sets over T, I usually use a Map[T, Int] with default 0.

**Comment by Ichoran** [comment]
Maps to integers would be considerably easier to use as a counted set if there was a `mapEntry(k: K, f: V => V)` method.

**Comment by EPronovost** [comment]
So do we want to implement this still?

**Comment by julienrf** [comment]
I think we should add a `MultiMap` collection type but as @odersky and @Ichoran mentioned it would be relatively easy to build a `MultiSet[A]` with a `Map[A, Int]` once we have methods presented in #251.
