### ISSUE TITLE
List.length and LazyList.length don't work

### ISSUE THREAD

**Issue by NthPortal** [scala/collection-strawman#146]
[`List.length`](https://github.com/scala/collection-strawman/blob/f55ad8ee920120da9d463b8cd2bfaebd8cb7253b/src/main/scala/strawman/collection/immutable/List.scala#L24) and [`LazyList.length`](https://github.com/scala/collection-strawman/blob/f55ad8ee920120da9d463b8cd2bfaebd8cb7253b/src/main/scala/strawman/collection/immutable/LazyList.scala#L31) always return `0` with their current tail-recursive implementation.

I think they need to be implemented similarly to [in `LinearSeqOptimized` in 2.12](https://github.com/scala/scala/blob/65980ea57893996d071b576a826004d5e3bbcc62/src/library/scala/collection/LinearSeqOptimized.scala#L47). I don't know if there should be a similar trait in the strawman from which both `List` and `LazyList` should inherit.

**Comment by julienrf** [comment]
Thanks for reporting this!
