### ISSUE TITLE
Difference in available operations between List and LazyList

### ISSUE THREAD

**Issue by odd** [scala/collection-strawman#154]
`LazyList` inherits `strawman.collection.immutable.SeqOps` whereas `List` inherits `strawman.collection.LinearSeqOps` (which extends `strawman.collection.SeqOps`). This means that the operations defined in `strawman.collection.immutable.SeqOps` (`prepend`, `append` and `updated`) are not available to `List` but to `LazyList`. `LazyList` still inherits the methods defined in `strawman.collection.LinearSeqOps` as `LazyList` extends `strawman.collection.LinearSeq` (which in turn extends `strawman.collection.LinearSeqOps`). 

Either `List` should be made to extend `strawman.collection.immutable.SeqOps` (like `LazyList`) or `LazyList` should no longer extend `strawman.collection.immutable.SeqOps` (but `strawman.collection.LinearSeqOps` instead). Which one to choose depends mainly on whether we want linear sequences to allow `append` and `updated`.

**Comment by julienrf** [comment]
We should have an `immutable.LinearSeqOps` and have both `List` and LazyList` extend it.

`append` and `updated` are inefficient on linear sequences, but for small sequences this is not a problem and having this methtod can be useful sometimes.
