### ISSUE TITLE
Scaladoc with images

### ISSUE THREAD

**Issue by Lasering** [scala/collection-strawman#155]
The documentation of [ReactiveX Observable](http://reactivex.io/rxscala/scaladoc/index.html#rx.lang.scala.Observable) uses images for a lot of the methods, things like:

Map:
![Map](https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/map.png)

Flatten:
![Flatten](https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/merge.oo.png)

Distinct:
![Distinct](https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/distinct.png)

I find these diagrams very useful to explain the functions on collections for people that are learning Scala for the first time.
I suggest including them in the scaladocs of the new collections as it would be extremely helpful for the newcomers.

ReactiveX uses the Apache2 license and makes the stencils used to create them available.

**Comment by laughedelic** [comment]
I think that idea about visualizing how collections work is good, but I think that these particular pictures could be better. I think that [reftree](http://stanch.github.io/reftree/) library looks more interesting for this, because it can show how different collections work internally and even animate it.

**Comment by Lasering** [comment]
These images were designed for ReactiveX so they have some particularities related with Observables. For the scala collections they could be improved. Also the examples I gave might have not been the better ones.

I disagree with showing how collections work internally. That will not be very useful for beginners. They don't even know how to use the collection and you are already trying to explain how the collections work internally, that is only going to confuse them even more.

The tool used to created the images is not important as long as the images convey what the functions do correctly.

**Comment by laughedelic** [comment]
> I disagree with showing how collections work internally. That will not be very useful for beginners. They don't even know how to use the collection and you are already trying to explain how the collections work internally, that is only going to confuse them even more.

I don't see why API documentation should be oriented solely on beginners. There are plenty of tutorials, blog-posts and other resources from community explaining basics for beginners. I think that official documentation should be a comprehensive source of information about library design concepts and implementations details _as far as they are relevant to the user_.

**Comment by Lasering** [comment]
> I don't see why API documentation should be oriented solely on beginners. There are plenty of tutorials, blog-posts and other resources from community explaining basics for beginners.

This argument goes both ways. I could make the same one geared towards not beginners.

> I think that official documentation should be a comprehensive source of information about library design concepts and implementations details _as far as they are relevant to the user_.

I agree but for me the _as far as they are relevant to the user_ stops at what the function does to the collection and not how it does it.

I think the better solution would be to include both types of images:

1. The simple ones that only show what the function does to the collection
2. The more advanced ones that show how the function does it.

This could be analogous to the [use case] the collection API has. Where by default the image showing the internals is collapsed.

**Comment by Ichoran** [comment]
@Lasering - The algorithm and data structure both matter.  They can make the difference between a program that is totally unusable (due to taking a million times too long) and one that works nicely.  It doesn't *always* matter, but to say "what the function does to the collection and not how it does it" is too simplistic.  Often, the best way to understand the limitations of the algorithm is to clearly understand the data structure.

**Comment by Lasering** [comment]
I agree and like I said both type of images should be included. I just think the simple ones should be more prominently displayed. For example the function [`map` on a `Seq`](http://www.scala-lang.org/api/current/scala/collection/Seq.html#map[B](f:A=>B):Seq[B]) is displayed by default as `def map[B](f: (A) ⇒ B): Seq[B]` however the real signature is `def map[B, That](f: (A) ⇒ B)(implicit bf: CanBuildFrom[Seq[A], B, That]): That`. This is possible because scaladoc gives us the `use case` annotation. The more advanced image could be included just in the `use case` annotation where as the simple image could be included in the "normal" scaladoc, outside of the `use case`.

**Comment by nafg** [comment]
Is this for the scaladocs or something like docs.scala-lang.org?

**Comment by SethTisue** [comment]
closing since we are in the process of shutting down this repo. regardless, this could still go forward in some form.

personally, I think docs.scala-lang.org would be an appropriate place for this, but perhaps there's no consensus in the best location.

**Comment by jvican** [comment]
I ported this to https://github.com/scala/docs.scala-lang/issues/1107.
