### ISSUE TITLE
Collection meeting

### ISSUE THREAD

**Issue by szeiger** [scala/collection-strawman#157]
Since @julienrf is still on vacation and nobody else seems to be around for a meeting today, let's start collecting topics for the next one:

- PF type inference problems in Dotty: https://github.com/scala/collection-strawman/pull/117 - I fixed it in Scala 2.13 but the Dotty typechecker is quite different and it wasn't clear to me if it's the same bug or something different

- State of collection laws

- It looks like all the design problems are solved so we can take the risk of adding more code. Are Spandex (https://github.com/scala/collection-strawman/pull/52), Steque (https://github.com/scala/collection-strawman/pull/88) and ArrayDeque (https://github.com/scala/collection-strawman/pull/49) good to clean up and merge? (This doesn't mean they would be merged into Scala in this state; we need to decide what to keep and under which name after we have more comprehensive benchmark results)

- By-name right-associative operators in Dotty? https://github.com/scala/collection-strawman/issues/127

- Merge `withFilter` (#165)?

- Merge `StrictOptimizedSeqOps` (#161)? Only two of the three overrides are actually used by a concrete collection (`List`)

- Priority of implicits (see #168)

**Comment by odd** [comment]
Spandex (#52) is good to go.

**Comment by julienrf** [comment]
Thanks @szeiger for taking care of that :)

> It looks like all the design problems are solved

I’m still not sold on the way we integrate `String` and `Array` decorators and the way we implement the `View` hierarchy. (see #134 and #78)

> State of collection laws

FTR, I created a branch to integrate unit tests ([here](https://github.com/scala/collection-strawman/compare/tests)) but I didn’t integrate https://github.com/scala/scala-collections-laws in it (yet). We should obviously add these tests, but the infrastructure looked a bit more complex than the unit tests.

> By-name right-associative operators in Dotty?

> PF type inference problems in Dotty

Could you open issues in the Dotty repo? (maybe you already did that, I didn’t check)

**Comment by Ichoran** [comment]
I'm working on collections-laws.  I have permission from Adriaan to rework it (with the `sourcecode` macros I can put a lot more out of weird custom config files and into Scala code without losing good error reporting--actually it's close to a complete rewrite of the code-generation logic).  Once I'm done with that, I'll port it to the strawman collections.  Pre-rewrite, it's pretty unfriendly.

**Comment by julienrf** [comment]
Hey, if you have time to review #165 before the meeting that would be great!

**Comment by pathikrit** [comment]
ArrayDeque is good to go (#49). Honestly ArrayDeque is better stack than current mutable.Stack and a better queue than current mutable.Queue and can also serve as a drop-in replacement for ArrayBuffers.

**Comment by julienrf** [comment]
@Ichoran Would you have some time to review #49? I think that would be valuable.

**Comment by Ichoran** [comment]
@julienrf - I won't be able to get to it until tomorrow evening.  Hopefully I'll have a long enough block of time then.

**Comment by Ichoran** [comment]
@julienrf - Didn't quite make it to the end but I think I hit all/almost all the important and semi-important points.
