### ISSUE TITLE
Add a MapView type providing lazy Map operations

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#160]
Similar to `IndexedView[A]`, we might want to add a `MapView[K, V]` collection type providing map-like transformation operations.

We have to figure out how the `View` hierarchy should coexist with the `Iterable` hierarchy.

**Comment by lrytz** [comment]
There's also `SeqView`. In 2.12, `List(1,2).view.reverse` works (https://github.com/scala/scala/blob/2.13.x/test/files/run/ReverseSeqView.scala)

**Comment by julienrf** [comment]
@lrytz For `reverse` I’m wondering whether we should support it at all in `SeqView`. It is possible to delay the process of reversing the underlying collection, but that process will reverse the whole collection at once (it can not be fused with other intermediate transformations).
