### ISSUE TITLE
Incorrect benchmarks charts

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#163]
The horizontal scale messes with zero:

![concat](https://user-images.githubusercontent.com/332812/28355418-3271d504-6c64-11e7-9d86-bad7a3b42c5f.png)

**Comment by marcelocenerine** [comment]
I think I have a fix for this. Can I have this issue assigned to me? I will be posting a PR shortly.

There are methods that can throw exceptions when the collection size is == 0 (e.g. tail, head, ...). In that case JMH fails the particular benchmark and does not report measurements. How would you like me to handle that case?

**Comment by julienrf** [comment]
In the case of `concat` (shown above) there should be no problem with empty collections. Are you sure this is the origin of the problem?

**Comment by marcelocenerine** [comment]
No, it is not related. It's just that the measurement for `tail` when size is 0 would be missing in the chart. I just wanted to confirm that this is the  expected outcome (although the answer is likely obvious ;))

**Comment by julienrf** [comment]
Closed by #212
