### ISSUE TITLE
Specialize for small number of elements

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#170]
`Set` and `Map`, for instance.

**Comment by EPronovost** [comment]
What sorts of specializations would you mean?  For storage, I could think of using an `Array` or `List` for a `Set` if it's sufficiently small.  Or do you mean algorithm optimizations, like switching from merge sort to bubble sort for sufficiently small sequences?

**Comment by julienrf** [comment]
Sorry, this ticket is not detailed :) 

The idea is to create implementations of HashSet and HashMap for 1, 2 and 3 elements and measure the performance improvements with the benchmarks. 

You can see how that's done in the current collections (I think they are named HashMap1, HashMap2, etc)

**Comment by EPronovost** [comment]
Where is `HashMap2` implemented?  I only found `HashMap1`, and then `HashTrieSet` for n > 1.

**Comment by julienrf** [comment]
In the current collections, `HashMapN` are here: https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/immutable/Map.scala#L95-L212, and `SetN` are here: https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/immutable/Set.scala#L64-L223.

**Comment by julienrf** [comment]
Hey @EPronovost are you currently working on this issue? I was thinking of working on it but I don’t want to step on your toes :)

**Comment by EPronovost** [comment]
@julienrf Yes.  I wrote a `HashSet2` yesterday.  The existing collections library goes up to `Set4`.  How far should we go?  How can I measure improvements in performance?

**Comment by julienrf** [comment]
Awesome! You can just run the `HashSetBenchmarks` with the following sbt command:

~~~
timeBenchmark/charts HashSetBenchmark
~~~

Both the `HashSetBenchmark` and `ScalaHashSetBenchmark` will run and produce images with charts in the `target` directory. However, there is a known issue with the charts generation (see #163) so you might want to temporarily disable the size `0` in the benchmarks.

**Comment by EPronovost** [comment]
@julienrf https://github.com/EPronovost/collection-strawman/commit/fcac8a3a645e8c4dba12cd71c7bd7075f3050f12

**Comment by julienrf** [comment]
Thanks for the pointer. Is it fine for you if I merge your commit and continue on top of it?

**Comment by EPronovost** [comment]
Sure thing!  What are the permissions settings for me contributing to the main repo?

**Comment by julienrf** [comment]
I think I will just cherry-pick your commit. Otherwise you can open a PR if you want to.

**Comment by EPronovost** [comment]
Sounds good go ahead.

**Comment by EPronovost** [comment]
@julienrf I can open a PR as well, but what branch should I target?

**Comment by julienrf** [comment]
Closed by #216
