### ISSUE TITLE
Add method distinct

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#175]
What do you think of a view based implementation that would use a `HashSet` to remember the traversed values? Thus, it would preserve laziness when used on views and `LazyList`.

**Comment by Ichoran** [comment]
I wouldn't do that for eager collections (s.c.i.HashMap is slow), but it's a reasonable strategy for lazy ones.  I think views will work more like eager collections in that regard, so they can take the same strategy but should use a mutable map (which may be the eager strategy also).

**Comment by joan38** [comment]
Is there any plan to add a `distinctBy` function?

**Comment by julienrf** [comment]
@joan38 Maybe. I find it useful too. I would love to have a generic way to implement these xxxBy methods (maxBy, sortBy, etc), though.
