### ISSUE TITLE
Migration to `scala` namespace (instead of `strawman`)

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#179]
In our last meeting we settled on the fact that we should move to the `scala` namespace as soon as possible. I updated the [roadmap](https://github.com/scala/collection-strawman#roadmap) accordingly. However I’m still not convinced that it’s the right time. Here are the pros and cons of moving to the `scala` namespace:

## Benefits of moving to `scala`

- we can reuse the standard test suite with very few changes (otherwise we would have to migrate the test suite to the `strawman` namespace and then eventually re-migrate everything to `scala`)
- `Array` and `String` decorators just work (since they provided by `Predef`)
- `Range` syntax (e.g. `1 to 10`) just works (since it’s provided by `Predef`)
- users don’t need to change their imports or to un-import the default collections
- migrating the compiler itself to use the strawman will be easier

## Benefits of staying in `strawman`

- easier to release: we just release a library that’s cross compatible with Scala 2.12, 2.13 and Dotty (otherwise we would have to release custom versions of the Scala and Dotty compilers -- and it might be a bit difficult to build custom versions of Scala and Dotty from the same strawman repository)
- maybe easier to play with, for users? Since they can co-exist with the standard collections, a project can use both at the same time
- performance comparison with the standard collections is easier to setup

Do I forget something? Leave a comment and I’ll update the description.

**Comment by Ichoran** [comment]
Cross-implementation benchmarking is easier if you leave it the way it is.

**Comment by lrytz** [comment]
One aspect that you cannot (easily) while staying in `strawman` is running the compiler using the new collections (https://github.com/scala/scala/blob/v2.12.2/src/reflect/scala/reflect/internal/Definitions.scala#L432-L457).

On the last Scala meeting we (very briefly) talked about this, and Martin mentioned the idea of releasing a Scala 2.12 distribution with the new collections swapped in. However, that doesn't really make it much easier to try out the new collections (except for projects without dependencies): such a release would not be binary compatible, dependencies released against 2.12.x would not work.

How about doing both, i.e., creating a branch where things are moved to `scala`? That should not be a source of many merge conflicts.

**Comment by julienrf** [comment]
> How about doing both, i.e., creating a branch where things are moved to `scala`? That should not be a source of many merge conflicts.

We can give that a try…

**Comment by julienrf** [comment]
@szeiger what’s the status of that? Is it possible to create a Scala distribution that uses strawman’s `master`?
