### ISSUE TITLE
Consider adding a lazyFoldRight method on LazyList

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#186]

**Comment by Ichoran** [comment]
To make it more grammatical, I'd suggest either `lazyFoldRight` or `foldRightLazily`.  I almost never use `LazyList` so I can't comment on whether this is valuable functionality.

**Comment by julienrf** [comment]
Yes, `lazyFoldRight` looks good. The motivation is that it’s a good way to lazily consume the elements of a `LazyList`, with the ability to short-circuit the termination (so, we can even use it on infinite lists).

**Comment by EPronovost** [comment]
Would this be along the lines of http://voidmainargs.blogspot.com/2011/08/folding-stream-with-scala.html ?

**Comment by julienrf** [comment]
Yes.

**Comment by EPronovost** [comment]
Is someone working on this already?

**Comment by EPronovost** [comment]
How does this look? https://github.com/EPronovost/collection-strawman/commit/924fafc21050c49193817710168e1d04f6e9a1f1
