### ISSUE TITLE
Add TrieMap collection type

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#195]
We should adapt the code of the current collection’s `TrieMap` to the strawman design.

**Comment by Ichoran** [comment]
Note that the existing (2.12) TrieMap fails to respect custom hashing on hash collisions.  We should make sure the adaptation here fares better.  See https://github.com/scala/bug/issues/10481

**Comment by julienrf** [comment]
I rebased to master and enabled the existing junit tests for `TrieMap`

**Comment by julienrf** [comment]
Closed by #204
