### ISSUE TITLE
Iterator.nextOption

### ISSUE THREAD

**Issue by nafg** [scala/collection-strawman#207]
See https://issues.scala-lang.org/browse/SI-4609

> Seth Tisue added a comment - 02/Aug/12 2:02 PM
> at https://groups.google.com/d/topic/scala-internals/_MAwjmUAXrU/discussion Martin writes (specifically in reference to nextOption): "There's a lot of benefit in keeping things stable. I think at the present time we do not want to consider changes to the API of collections. We simply do not have the bandwidth to process them and as you say we have bigger fish to fry. There might be a time in the future where we want to reopen the agenda of a re-design that then would touch many things. Most likely, though, it would involve moving functionality out into wrapper classes instead if in into the collections themselves."

Sounds like now might be a good time?

**Comment by EPronovost** [comment]
@nafg are you working on this?  If not I can do it

**Comment by EPronovost** [comment]
See pull request #218

**Comment by julienrf** [comment]
Closed by #218
