### ISSUE TITLE
Provide a LinkedHashMap implementation

### ISSUE THREAD

**Issue by jvican** [scala/collection-strawman#211]
The compiler uses `LinkedHashMap` in several places. The most notorious is `Implicits.scala` https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/typechecker/Implicits.scala#L151-L153.
  
Is there any plan to add `LinkedHashMap` to the strawman? Is there a current replacement for it?
  
The difference between a `HashMap` and a `LinkedHashMap` is that the latter preserves order of insertion.

**Comment by Ichoran** [comment]
I don't think anything is left out on purpose.  Nobody's gotten to it yet.  Probably @julienrf will be the one to do it

**Comment by EPronovost** [comment]
What's the difference between a `LinkedHashMap` as implemented and a more general `LinkedMap`?

**Comment by jvican** [comment]
I think a `LinkedMap` could be implemented with a tree instead of a hash table, so `LinkedHashMap <: LinkedMap` and `LinkedTreeMap <: LinkedMap`.

**Comment by julienrf** [comment]
@jvican `LinkedTreeMap` is confusing because the existing `TreeMap` uses the `Ordering` of the element type, not the insertion order.

**Comment by jvican** [comment]
@julienrf [I think it exists though](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java). It seems that it uses a tree just for efficient insertion and removal, unlike a `LinkedHashMap`.
