### ISSUE TITLE
Add zipWith operation

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#221]
It’s a generalization of `zip`, its signature would be the following:

~~~ scala
trait IterableOps[A, CC[_], C] {
  def zipWith[B, R](that: Iterable[B])(f: (A, B) => R): CC[R]
}
~~~

Semantically speaking, `(xs zip ys) map f` is equivalent to `xs.zipWith(ys)(f)`.

**Comment by marcelocenerine** [comment]
I'm submitting a PR shortly

**Comment by SethTisue** [comment]
we ended up adding `lazyZip` instead
