### ISSUE TITLE
Fix withDefault operation on Map

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#226]
`TreeMap(1 -> "one").withDefault("NaN") + (2 -> "two")` doesn’t return a `SortedMap`

**Comment by dhanesharole** [comment]
Is anyone working on this? Can I have a look?

**Comment by dhanesharole** [comment]
@julienrf I have raised [PR](https://github.com/scala/collection-strawman/pull/381) for this issue. Can you please review it and give some feedback ?
