### ISSUE TITLE
Consider adding a `merged` or `mergedWith` operation on `Map`

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#240]
As described here: https://github.com/jozic/scalax-collection#mergedwith

Note: in `collection.immutable.HashMap` we already have it and it is named `merged`. We could just pull it up to `collection.Map`.

**Comment by julienrf** [comment]
Second note: in #259 I added `mergeByKeyWith`, which is more general than `mergedWith`:

~~~
def mergedWith[K, V](`this`: Map[K, V], that: Map[K, V])(f: (V, V) => V): Map[K, V] =
  `this`.mergeByKeyWith(that) {
    case (Some(v1), Some(v2)) => f(v1, v2)
    case (Some(v),  None)     => v
    case (None,     Some(v))  => v
  }
~~~

**Comment by EPronovost** [comment]
So do we still want to implement `mergedWith`?

**Comment by julienrf** [comment]
I would just keep `mergeByKeyWith` for now.
