### ISSUE TITLE
Different names for fold operations

### ISSUE THREAD

**Issue by NthPortal** [scala/collection-strawman#243]
I find that the current naming for fold operations can be confusing, and would like to propose renaming them.

Currently, there are methods `foldLeft` and `foldRight`, with `foldSomeLeft`, `foldSomeRight` and `lazyFoldRight` proposed as well.

Let's take `Iterable.foldLeft` as an example. Is it being folded **to** the left, or **from** the left? Also, which way does the collection run: left-to-right, or right-to-left? From what I can tell, the collection runs left-to-right, and is being folded **from** the left (although it is equivalent to say it runs right-to-left, and is being folded **to** the left). The meaning of the methods is not immediately obvious, and may take several uses to remember what it means.

I propose instead using names such as `foldForward` and `foldBackward` (or similar), which have a couple of advantages:

- they do not suppose any direction for the collection, and will thus not conflict with a different direction a user had in mind (e.g. if they speak a language written right-to-left, top-to-bottom, etc.)
- there is no ambiguity of folding to or from the left, because "forward" and "backward" are only directions, and cannot be interpreted as locations

Despite the fact that the method names are longer, I think that `foldForward` and `foldBackward` would be better, clearer names, especially for beginners.

**Comment by Ichoran** [comment]
This is standard terminology, though, not just in Scala, and comes from the associativity of the underlying operation (`foldLeft` corresponds to left-associative parsing of `x0 ~ x1 ~ ... ~ xN` where `~` is the operation).  I think in such cases, especially when a method has already been introduced, that it's best to stick to standard terms.

There are a few exceptions where the naming is just atrocious (e.g. "kestrel" vs "starling" vs. "thrush" combinators) where one can reasonably argue that not only should one choose better names, but that one should even change existing names.  But I don't believe this is one of them.

**Comment by SethTisue** [comment]
@NthPortal thanks for the thoughtful suggestion. if we were starting from scratch, I think your proposed names would have a good chance. but at this stage in Scala's evolution, I'm afraid I agree with Rex.
