### ISSUE TITLE
Decide what kind of equality to use for maps and sets, and other operations

### ISSUE THREAD

**Issue by odersky** [scala/collection-strawman#246]
See: https://contributors.scala-lang.org/t/can-we-get-rid-of-cooperative-equality/1131/34

If we migrate away from co-operative equality, new collections should not use it anymore and should use `equals` and `hashCode` instead. Even if we do not migrate away, it might still be preferable to do this for performance reasons. 

Same holds for operations such as `indexOf` on `Seq`.

**Comment by julienrf** [comment]
A note about that: for `TrieMap` it is possible to use a custom equality. Do we want to generalize that? I think that would make sense. What is the performance overhead, though?

**Comment by Ichoran** [comment]
It would be great if we could implement custom equality that didn't have a performance penalty beyond what `scala.runtime.BoxesRunTime.equals2` and friends have.  Is there an easy way we can test this?  Maybe run the performance test on `TrieMap` with the custom equality commented out and regular `==` equality used in its place?

**Comment by julienrf** [comment]
I think what we will do on the collections will depend on what we decide about cooperative equality in general in Scala?

**Comment by odersky** [comment]
I don't have high hopes for cooperative equality in Scala. We might still introduce it in Dotty but that would then be transparent as gar as the collections are concerned. I agree that customizing equality is a win. Easy to do for mutable collections - just expose an overridable equals and hashCode operation. For immutable it looks more cumbersome to do it, though. We'd probably need an extra parameter (implicit or explicit).

**Comment by julienrf** [comment]
As long as Scala 2.13 keeps using cooperative equality, I think the collections should keep using cooperative equality as well.
