### ISSUE TITLE
Consider providing better support for traverse/sequence operations

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#247]
These operations have been mentioned several times in recent discussions initiated [here](https://contributors.scala-lang.org/t/which-operations-should-be-included-in-the-new-collections/1106/30).

One difficulty is that `traverse` and `sequence` involve two capabilities: `Traverse` and `Applicative`, so the best way to handle all possible combinations (e.g. `Option[Future[_]]`, `List[Future[_]]`, `Option[List[_]]`, `List[Option[_]]`, `List[Either[_, _]]`, etc.) is probably to use typeclasses. Currently in the standard library we only support `Future.sequence`, which works only for `Seq`s nested in `Future`s. If we want to support other types (ie. not only `List[Future[_]]` but also `Option[Future[_]]`), we should probably do it by using a typeclass.

But it would also be interesting to have these `sequence` and `traverse` methods available on other types than `Future`. Useful candidates would be `Option`, `Either` and `Try`.

See also [this previous discussion](https://github.com/scala/collection-strawman/issues/38#issuecomment-282759830)

**Comment by julienrf** [comment]
A few thoughts about that one.

On one hand, a typeclass-based design (with `Traverse` and `Applicative`) would provide the highest level of reuse: once you define N instances of `Traverse` and M instances of `Applicative` you can combine them to handle N×M situations.

On the other hand, the discoverability of the `traverse` and `sequence` operations would be rather poor. Today it is easy to find `Future.sequence` (and to understand what it does) just by browsing the Scaladoc. But if, instead, we only find an instance of `Applicative` in `Future`’s documentation, it is not obvious what it can be useful for.

A compromise might be to have the typeclass-based design (so that advanced users have the full power) but also define specialized forwarders in companion objects of `Applicative` instances (such as `Future`).

In summary, the changes we would have to apply would be the following.

1. Define `Traverse` and `Applicative` typeclasses
2. Define useful instances
    - For `Applicative`, those that come to my mind are: `Option`, `Future`, `Either`
    - For `Traverse`: `List`, `Option`, `Either`
3. Add forwarder methods in companion objects of `Applicative` instances. For instance, for `Future`:
   ~~~ scala
   object Future {
     def traverse[F[_], A, B](fa: F[A])(f: A => Future[B])(implicit F: Traverse[F], ec: ExecutionContext): Future[F[B]] = F.traverse(fa)(f)
     def sequence[F[_], A](ffa: F[Future[A]])(implicit F: Traverse[F], ec: ExecutionContext): Future[F[A]] = F.sequence(ffa)
   }
   ~~~
   For the sake of comparison, the current definition of these methods is the following:
   ~~~ scala
   object Future {
     def traverse[A, B, M[X] <: TraversableOnce[X]](in: M[A])(fn: A => Future[B])(implicit cbf: CanBuildFrom[M[A], B, M[B]], executor: ExecutionContext): Future[M[B]]
     def sequence[A, M[X] <: TraversableOnce[X]](in: M[Future[A]])(implicit cbf: CanBuildFrom[M[Future[A]], A, M[A]], executor: ExecutionContext): Future[M[A]]
   }
   ~~~
   I don’t think the one that uses `Traverse` is more complicated that the current one…

Last but not least: these changes would mainly impact the standard library, not really the collections. We should probably open an issue on scala/bug to get more feedback from the scala-library maintainers…

**Comment by dhanesharole** [comment]
Can I pick up this ? Is anyone working on it ?

**Comment by julienrf** [comment]
I think this one will be simpler to address after we have moved the code base to the scala/scala repository. (I shouldn’t have put the `ready` label…)

**Comment by Jasper-M** [comment]
It feels a bit awkward to only add `Traverse` and `Applicative` just for this purpose, but not have all related typeclasses and operations.

**Comment by julienrf** [comment]
Continued here: https://github.com/scala/bug/issues/10934
