### ISSUE TITLE
In-place mapping and sorting to mutable collections

### ISSUE THREAD

**Issue by japgolly** [scala/collection-strawman#25]
When working with mutable collections, I sometimes find it useful to be able to map and sort in-place.

I wrote a little utility to do this; have a look to see what I mean:
https://github.com/japgolly/microlibs-scala/blob/master/stdlib-ext/shared/src/main/scala/japgolly/microlibs/stdlib_ext/MutableArray.scala

If we agree it's desirable, I'd be willing to create a PR here to apply similar functionality.

**Comment by julienrf** [comment]
Hi @japgolly, that’s also something we plan to add to mutable collections, see https://github.com/scala/collection-strawman/blob/master/src/main/scala/strawman/collection/mutable/Seq.scala Tell us what you think :)

**Comment by japgolly** [comment]
Oh cool, I'm glad it's been thought of. I don't find the current implementation useful though, it's all `A => A` which is so rarely what you want or need when you want to map in place.

I just pushed a change to my `MutableArray` link above, please have another look. This is the kind of thing I envision.
* Map from A => B.
* Has map fusion / mapping is lazy.
* In addition to just `.sortBy` there's also `.sortBySchwartzian`. The pre and post map operations compose with other map operations before and after the sort.

This is the kind of use case I have in mind (it's an excerpt of real code of mine):
```scala
      MutableArray(tagMap.valuesIterator.map(_.tag))
        .sortBySchwartzian(_.key.value |> normaliseStringForSorting)
        .map(_.id)
        .toList
```

**Comment by japgolly** [comment]
Oh and `.map` fuses with `CanBuildFrom`/`.to[_]`
i.e. `.map(f).to[List]` is Θ(n), not Θ(2n)

**Comment by julienrf** [comment]
> I don't find the current implementation useful though, it's all A => A which is so rarely what you want or need when you want to map in place.

On the other hand it is dangerous to support `A => B`:

~~~ scala
val xs = ListBuffer(1, 2, 3)
val ys: Iterable[Int] = xs
xs.mapInPlace(_.toString)
println(ys.head) // ClassCastException
~~~

**Comment by japgolly** [comment]
I only ever use mutability in very small, local contexts. It may be that I'm not fully considering how the community as a whole, would use these.

Personally, I think the danger of in-place `A => B` here perfectly acceptable. Mutability goes hand-in-hand with danger and the requirement to be careful. I'd say that mutable collections are always fast and require caution for correctness, where as immutable collections are always correct and require caution to be fast (eg. linked list prepend vs append).

**Comment by Ichoran** [comment]
@japgolly - If you want to mutate in place like that, which is horribly dangerous, use this workaround:

```scala
scala> collection.mutable.ArrayBuffer(1, 2, 3)
res1: scala.collection.mutable.ArrayBuffer[Int] = ArrayBuffer(1, 2, 3)

scala> res1.transform(((i: Int) => i.toString).asInstanceOf[Int => Int]).asInstanceOf[collection.mutable.ArrayBuffer[String]]
res2: scala.collection.mutable.ArrayBuffer[String] = ArrayBuffer(1, 2, 3)

scala> res2.head.getClass.getName
res3: String = java.lang.String

scala> res1.head
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
```

This kind of thing isn't something the standard library should support.  It's far too easy to get it wrong and cause problems.  If we had a notion of a variable being consumed (lifetime-like analysis), we could support it, but barring that it's a footgun.

**Comment by julienrf** [comment]
@japgolly Is it OK if we close this issue? (Since in-place mutating methods are already part of our design)

**Comment by LPTK** [comment]
Would it make sense to have a mutable `groupBy`, which would physically group the elements within the mutable collection and return views indexing into it?

It would look like this:
```scala
> val arr = ArrayBuffer(1,2,3,4,5)
arr: ArrayBuffer[Int] = ArrayBuffer(1, 2, 3, 4, 5)
> arr.groupBy(_ % 2)
res0: Iterable[(Int, View[Int])] = ArrayBuffer((0, ArrayBufferView(2, 4)), (1, ArrayBufferView(1, 3, 5)))
> arr
res1: ArrayBuffer[Int] = ArrayBuffer(2, 4, 1, 3, 5)
```

I could see it used in perf-sensitive code, since it avoids rebuilding expensive collections as normally done by groupBy (i.e., a mutable Map with mutable buckets, followed by an immutable Map with buckets of the same type as the current collection).

**Comment by Ichoran** [comment]
I doubt this will matter enough to warrant the extra code except in very specialized cases where domain-specific knowledge will need to be employed anyway.  You can shuffle by putting an arbitrary sort order on the groups, but that is `O(n log n)`; or you can allocate one buffer per group, but that's most of the overhead anyway.

**Comment by japgolly** [comment]
I'm terribly sorry, I forgot about this completely.

> It's far too easy to get it wrong and cause problems. If we had a notion of a variable being consumed (lifetime-like analysis), we could support it, but barring that it's a footgun.

As long as one doesn't store a reference to it, it's completely safe and performant. But I take your point, once in the stdlib users *will* misuse it.

> Is it OK if we close this issue? (Since in-place mutating methods are already part of our design)

Yes, no problem. It was just a thought :) I'll close it now
