### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by szeiger** [scala/collection-strawman#27]
We should spend some time in Q2 on automatic migration of user code to the new collections. The main tool will probably be [ScalaFix](https://github.com/scalacenter/scalafix) but [JetBrains' Migrations API](https://blog.jetbrains.com/scala/2016/11/11/intellij-idea-2016-3-rc-scala-js-scala-meta-and-more/#more-1642) should also be considered.

Migration could either be performed by an IDE or an automated tool. We need to perform tests to see how much manual work is still required after the automatic migration on some popular Scala code bases.

**Comment by julienrf** [comment]
We should provide a decent support for cross-building, not just migrating to the new framework.

**Comment by szeiger** [comment]
We're working on both so I'm closing this rather abstract ticket.
