### ISSUE TITLE
Finer-grained Iterable .sum & .product implementations, and `Numeric`.

### ISSUE THREAD

**Issue by MichaelJAllen** [scala/collection-strawman#281]
One relatively minor point that has bothered me about the existing collections is the reliance upon `Numeric` in `Iterable.sum` and `Iterable.product`. `Iterable.sum` relies upon `Numeric.zero` and `Numeric.plus`, while `Iterable.product` relies upon `Numeric.one` and `Numeric.times`.

`Numeric` is a fairly noisy type with a _fat interface_ that requires conversion to and from a number of _value types_ (`.fromInt`, `.toDouble`, etc.), as well as other common numeric operations.

However, the requirements for `Iterable.sum` and `Iterable.product` are really just simple addition and multiplication _monoids_, respectively.

Currently, in order to enable `Iterable.sum` and `Iterable.product` for custom value types, it is necessary to create implicit `Numeric` instances for those types. However, not all of the functions defined by `Numeric` make sense for all value types.

As a case in point, I have  a set of types representing physical quantity measurements (such as _time_, _length_, _velocity_, etc.). To avoid issues relating to the units in which these measurements are expressed, I prefer not to allow conversion to/from primitive value types such as `Double`. However, addition and subtraction of measurements of the same type are clearly possible. Multiplication and division are more complicated, because, for example, a _length_ multiplied by a _length_ results in an _area_, a _length_ divided by a _time_ results in a _velocity_, while a _length_ divided by a _length_ results in a unitless value.

So, while I can easily create _addition monoids_ (and can therefore support the `sum` operation on, say, a list of _length_ values), _multiplication_ monoids are more of a challenge. But creating `Numeric` instances requires that I implement the majority of its members as throwing exceptions.

There has to be a better way.

What I'm proposing is that these operations rely on implicit monoid instances instead. This would require `Numeric` to be implemented from addition and multiplication monoids, for backwards compatibility (so that `Numeric` instances fulfill the monoid requirements). We could then also define folds in terms of monoid instances.

Any ideas?

**Comment by julienrf** [comment]
What solution do you prefer to distinguish addition and multiplication `Monoid` instances? What would be the signature of `sum` and `product`?

Also, it’s a one liner to implement a generic operation that folds a collection using a monoid, given your definition of `Monoid` (e.g. from scalaz, cats, play-functional, etc.):

~~~ scala
def foldLeftWithMonoid(iterable: Iterable[A])(implicit monoid: Monoid[A]): A = iterable.foldLeft(monoid.zero)(monoid.combine)
~~~

So, I’m not sure we should spend a lot of energy in a sophisticated generic system that uses “tagged” monoid instances.

**Comment by MichaelJAllen** [comment]
I agree that these are one-line implementations (given available types, implicits, etc.), but if that's the objection, why even bother to have `sum` and `product` at all? I'd say, it's because they're both convenient and self-documenting. I also agree that there are plenty of support libraries for this type of problem - but we're talking about the _standard library_, so it should just work out of the box. :-)

So here's my stab at your suggestion. This first one is not particularly clever:

```Scala
trait AdditionMonoid[A] {
   val zero: A
   def plus(a: A, b: A): A
}

trait MultiplicationMonoid[A] {
  val one: A
  val times(a: A, b: A): A
}

// Numeric instances are also AdditionMonoid and MultiplicationMonoid instances, for backward
// compatibility.
trait Numeric[A]
extends Ordering[A]
with AdditionMonoid[A]
with MultiplicationMonoid[A] {
  // etc.
}

// I guess these definitions are in TraversableOnce, not Iterable. :-)
trait TraversableOnce[+A] {
  // etc.

  def sum[B <: A](implicit num: AdditionMonoid[B]): B = foldLeft(num.zero)(num.plus)
  def product[B <: A](implicit num: MultiplicationMonoid[B]): B = foldLeft(num.one)(num.times)

  // etc.
}
```

This would support the finer-grained `sum` and `product` support I requested. In my example, I could just define implicit `AdditionMonoid` instances for my value types. `product` wouldn't work for my types, because there would be no `MultiplicationMonoid` instances defined. Meanwhile, existing `Numeric` implicit instances should continue to work (I think).

However, assuming that `Monoid` is so fundamental that it should be in the standard library, then it might also be possible to do the following:

(BTW: I'm just thinking out loud here; I accept that this may not be feasible or desirable. Also, I'm deliberately ignoring the relationship to a `SemiGroup` type, which would also suit `reduce` operations.)

```Scala
trait Monoid[A] {
  val empty: A
  def combine(a: A, b: A): A
}

implicit final class AdditionMonoidToMonoid[A](am: AdditionMonoid[A])
extends Monoid[A] {
  override val empty = am.zero
  override def combine(a: A, b: A) = am.plus(a, b)
}

implicit final class MultiplicationMonoidToMonoid[A](mm: MultiplicationMonoid[A])
extends Monoid[A] {
  override val empty = mm.one
  override def combine(a: A, b: A) = mm.times(a, b)
}

trait TraversableOnce[+A]
// etc.
{

  // etc.

  // Alternative foldLeft using a monoid.
  def foldLeft[A](m: Monoid[A]) = foldLeft(m.empty)(m.combine)

  // Alternative sum and product definitions building on the above.
  def sum[B <: A](implicit num: AdditionMonoid[B]) = foldLeft(num) // Implicit conversion to monoid.
  def product[B <: A](implicit num: MultiplicationMonoid[B]) = foldLeft(num) // Ditto

  // etc.
}

This latter code might be more concerning, but would the former be too sophisticated to implement?

**Comment by julienrf** [comment]
I think `sum` and `product` have their place in the core because they generally useful when users manipulate numbers.

I don’t think we should introduce `AdditionMonoid` and `MultiplicationMonoid` just for them, though. Do you have an example of a datatype which is not `Numeric` but for which you would like to implement both `AdditionMonoid` and `MultiplicationMonoid`?

**Comment by MichaelJAllen** [comment]
How about a _probability_? You can add and multiply them, but conversion to integer types makes no sense whatsoever.

**Comment by julienrf** [comment]
> but conversion to integer types makes no sense whatsoever

Why? Aren’t they just floating point numbers?

**Comment by MichaelJAllen** [comment]
Sure, in the range [0, 1]  ;-)

**Comment by julienrf** [comment]
I’m closing this issue because I think it would be a too big change compared to the benefits it would bring.
