### ISSUE TITLE
Remove withFilter?

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#288]
Why do we special case `filter` to be lazy in for-comprehensions but not `map` or `flatMap`?

I would recommend to just use `.view` to get the lazy semantics:

~~~ scala
for {
  x <- xs.view
  if x % 2 == 0
} yield x + 1
~~~

**Comment by marcelocenerine** [comment]
Isn't it the goal of #164 with `empty`?

**Comment by sjrd** [comment]
> Why do we special case filter to be lazy in for-comprehensions but not map or flatMap?

Probably because `filter` is never a terminal operation in a for-comprehension, whereas `map` and `flatMap` are.

**Comment by julienrf** [comment]
@marcelocenerine You are right, with the changes proposed in #164 we could produce a better desugaring for guards, which wouldn’t use `filter` at all but `point` and `empty`.
