### ISSUE TITLE
Improve performance compared to the current collections

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#290]
In general the strawman is slower than the current collections (~1.5x, in general). We should identify the reasons of this slowdown and fix it.

**Comment by Ichoran** [comment]
Most of it is probably the extra indirection through views, but we should look carefully at the reasons.

**Comment by julienrf** [comment]
This ticket has been mostly solved by #305 but some performance issues remain, therefore I’m not closing this ticket yet.

**Comment by xeno-by** [comment]
Is there more detailed information on what performance issues still remain? Is there a publicly available graph of benchmarks like the one provided by scala/compiler-benchmark?

**Comment by julienrf** [comment]
No, currently we have no public infrastructure for that. I manually run a subset of the benchmarks on a dedicated machine (even running a subset takes about 24 hours). We use Oracle’s JVM 1.8.0_121. Here are the issues I’ve observed on `Vector`:

---

![access_init](https://user-images.githubusercontent.com/332812/33420421-c3aa1bb8-d5ae-11e7-9cd7-d241bae2b80a.png)

Lower is better, the yellow line shows the execution time of the `init` operation on strawman’s `Vector`, whereas the green line shows the performance of the current (Scala 2.13) `Vector`. Pay attention to the fact that scales are logarithmic. If we look at the numbers, for size = 17, the average time taken by the `init` operation is 35 ns (±0.8) in the strawman whereas it is 27 ns (±0.2) in the standard collections. So in that case we see a 1.3x slowdown.

---

![access_tail](https://user-images.githubusercontent.com/332812/33420724-f3446206-d5af-11e7-8782-d5157c0f0d49.png)

For `tail` the difference is more visible. Here, at size = 15 we see 40 ns (±0.6) for the strawman and 24 ns (±0.3) for the current collections: 1.67x slowdown. And we observe this slowdown on all the tested sizes.

---

![expand_appendall](https://user-images.githubusercontent.com/332812/33420955-d0ee588c-d5b0-11e7-87f1-3f372706d0a4.png)

For `:++`, we observe a 1.7x slowdown for small sizes and then up to a 200x slowdown for large collections. (on the same image we can see that the situation is different for `List`: strawman’s lists are significantly faster for small sizes and significantly slower for large sizes…)

---

![traverse_foldright](https://user-images.githubusercontent.com/332812/33421305-eb69fe72-d5b1-11e7-84af-d608cc4457bb.png)

That one is for `List`: `foldRight` is in general slower in the strawman, up to 9x slower.
