### ISSUE TITLE
"java.lang.ClassFormatError: Illegal field modifiers" when testing on Scala 2.13 nightly

### ISSUE THREAD

**Issue by SethTisue** [scala/collection-strawman#296]
`++2.13.0-pre-74ca535` followed by `collectionsJVM/test` gives:

```
[info] Test strawman.collection.test.StrawmanTest.initializationError started
[error] Test strawman.collection.test.StrawmanTest.initializationError failed: java.lang.ClassFormatError: Illegal field modifiers in class strawman/collection/immutable/List: 0x1A, took 0.005 sec
```

this does not occur with `++2.13.0-M2` (nor, if the 2.12 community build can be believed, with the latest 2.12 nightly)

discovered by the Scala 2.13 community build. attn @szeiger

**Comment by SethTisue** [comment]
seems like possibly a back end thing... @lrytz?

**Comment by hrhino** [comment]
So, `0x1A` is `ACC_PRIVATE | ACC_STATIC | ACC_FINAL`, which seems legit.

I wouldn't be here but for the fact that I recently got scala/scala#6141 merged, which creates a `private static final long serialVersionUID` field. I ~~wonder if~~ hope it's not that.

**Comment by hrhino** [comment]
So it's that, and it's that `List` has a `@serialVersionUID` annotation, which is normally useless and now deleterious (`private static final` fields are _verboten_ on interfaces).

I can't assign this to me but I'll take care of it.
