### ISSUE TITLE
Add ceiling and floor methods for TreeSet and TreeMap 

### ISSUE THREAD

**Issue by Psycho7** [scala/collection-strawman#298]
`floor` method returns the max value less than or equal to a given value. Since TreeSet and TreeMap are based on red-black tree, `O(logn)` should be the complexity of this kind operations. However, currently there is no way to to this in `O(logn)`. For example, `TreeSet(1, 3, 5).to(4).max` will return the max value less than 4, which is 3. However, an intermediate TreeSet will be created (and rebalanced) because `to` method was called, thus the complexity is worse than `O(logn)`. I'm not sure if it's `O(nlogn)` or `O(n)`.

In Java, `floor` and `ceiling` are provided for TreeSet, and `floorKey`, `floorEntry`, `ceilingKey` and `ceilingEntry` for TreeMap. I think they should be provided Scala in a elegant way.

**Comment by acruise** [comment]
+1, I've wanted these before and gone back to j.u equivalents

**Comment by julienrf** [comment]
Also, [here](https://users.scala-lang.org/t/when-using-treeset-how-to-get-ceiling-or-floor-value-efficiently/1920) is a relevant discussion.

**Comment by Psycho7** [comment]
What do those label mean? I'm glad to contribute if it is not done yet.

**Comment by julienrf** [comment]
“low hanging fruit” means that it’s an affordable issue (it doesn’t require a lot of work). “ready” means that anyone can start working on it! If you want to work on it I can pass it in “in progress” state :)

**Comment by Psycho7** [comment]
More than glad to help. :)

**Comment by julienrf** [comment]
Awesome, thanks!

**Comment by Psycho7** [comment]
I found that `maxBefore` and `minAfter` in `mutable.RedBlackTree` and they are used in `mutable.TreeMapVew` and `mutable.TreeSetView`. These methods can do exactly what I want and are elegant. Actually these methods are implicitly called when you call `head / last` on `TreeSetView / TreeMapView` with `from / to` enabled. 

However, there is no immutable `TreeMapView` or `TreeSetView`. Is there any plan to have them?

Another question is, should I implement these methods in `TreeMap` / `TreeSet` directly and make them public?

**Comment by julienrf** [comment]
> However, there is no immutable TreeMapView or TreeSetView. Is there any plan to have them?

No. You can add them if they are necessary (but it doesn’t look like it’s the case).

> Another question is, should I implement these methods in TreeMap / TreeSet directly and make them public?

Yes!

**Comment by Psycho7** [comment]
Good to hear that!

Another question, maybe a little off the topic though, what are those `View` for? Looks like for performance in this case.

**Comment by julienrf** [comment]
These `View`s compute a ranged projection of the underlying collection. In the case of mutable collections, changes made to the projection also update the underlying collection and _vice versa_. They are different from the new `View`s that we introduced in the strawman, whose transformation operations (`map`, `filter`) are lazy. We should probably rename `TreeMapView` into `TreeMapProjection` or `TreeMapSlice` to avoid the confusion (but that’s out of the scope of this issue).

**Comment by Psycho7** [comment]
Wow. Thanks for the clarification!
