### ISSUE TITLE
Move `take`, `drop` and friends in a `StableIterable` trait

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#30]
See https://github.com/scala/collection-strawman/pull/24/files#r100122953 for background.

**Comment by Ichoran** [comment]
I don't like this idea.  There is nothing wrong with saying "I want 15 elements even though I don't know what the order will be."

And it's not backward-compatible.

Slice is a bit trickier.  It doesn't make much sense outside of a stable order, but on the other hand it's a natural consequence of having take and drop.

**Comment by odersky** [comment]
I agree with @ichoran. "take 3 elements from a set" is quite natural. 

In general, it's the philosophy of Scala collections that any operation should work for any collection as long as that this makes sense in some situations. So far, attempts to tweak that met a lot of resistance. In fact, there are quite a few dimensions in which one might want to restrict operations:

 - finiteness: e.g. length makes no sense for infinite streams
 - partiality: head, tail are undefined on empty lists, apply could be out of bounds
 - sharing: +, map on mutable collections lose sharing
 - stable ordering: head, tail on sets are underspecified
 - efficiency: :+ is linear on lists

I have not seen a simple design yet that reflects all of these concerns. So the current policy is to stay silent about them.
