### ISSUE TITLE
Rename TreeMapView and TreeSetView to avoid confusion with Views

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#301]
We should replace the “View” suffix with something different (e.g. `TreeMapSlice`, `TreeSetProjection`, …).

**Comment by jiminhsieh** [comment]
@julienrf Do you think it's a better idea of using the same postfix? 
1. `TreeMapProjection` and `TreeSetProjection`  
or
2. `TreeMapSlice` and `TreeSetSlice`

**Comment by julienrf** [comment]
Sure!

I do have a slight preference for the `Projection` suffix, btw.

**Comment by jiminhsieh** [comment]
> I do have a slight preference for the Projection suffix, btw.
We are on the same page. :)
