### ISSUE TITLE
Consider adding BiMap

### ISSUE THREAD

**Issue by xmiliany** [scala/collection-strawman#303]
To quote Guava: 

> A bimap (or "bidirectional map") is a map that preserves the uniqueness of its values as well as that of its keys. This constraint enables bimaps to support an "inverse view", which is another bimap containing the same entries as this bimap but with reversed keys and values.

Is there any interest in adding something like this to the new collections library?

**Comment by julienrf** [comment]
Thanks for the suggestion. I think this is a valid use case but maybe not frequent enough to be part of the core. We might include it in collections-contrib or maybe even in its own separate module.
