### ISSUE TITLE
Consider adding dedupe to Seq

### ISSUE THREAD

**Issue by joroKr21** [scala/collection-strawman#310]
Is there place for a `Seq.dedupe` method in the new collections library?

It's similar to `distinct` but removes only consecutive duplicates. I find myself needing this from time to time. For reference, Clojure has it: https://clojuredocs.org/clojure.core/dedupe.

**Comment by SethTisue** [comment]
this seems not to have garnered sufficient support.

**Comment by NthPortal** [comment]
This seems like a good candidate for collection-contrib
