### ISSUE TITLE
Add a rule checking that existing user code don’t compare Iterables

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#313]
Iterables are not comparable anymore. We should detect when such comparison happen in existing code bases and emit a warning.

**Comment by marcelocenerine** [comment]
@julienrf , could you clarify a bit more?

**Comment by julienrf** [comment]
I thought that in the current collections we had overridden `equals` in `Iterable` to compare the collection elements, but I just checked and it’s not the case. So, what we do with equality in the strawman and in the current collection is the same.
