### ISSUE TITLE
Make `knownSize` in `Iterator` non final and override it for `IndexedSeq` iterators

### ISSUE THREAD

**Issue by odd** [scala/collection-strawman#323]
The `knownSize` method in `Iterator` is final and returns `-1` which signals that the size is not efficiently knownable. But this is not true for `IndexedSeq` inheritors, so they should be able to override it in their iterator implementations. This would allow any later transformations on the iterators to take advantage of the known size (for example by preallocating buffers of the right size).

**Comment by julienrf** [comment]
> This would allow any later transformations on the iterators to take advantage of the known size (for example by preallocating buffers of the right size).

Do you have examples of such operations?
