### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#327]
We should make sure that all operations are tested.

We should use https://github.com/scala/scala-collections-laws as soon as it is ready.

**Comment by Ichoran** [comment]
It is ready to be implemented for collections-laws!  (The refactoring branch.)

I am really busy trying to finish up a year-end project so can't work on it for the rest of the year.  I could next year, if you'd like, or at least advise you on how to port the tests the strawman collections.

**Comment by julienrf** [comment]
Oh sorry I didn’t think of looking at your fork! I thought that branch hasn’t been pushed, but now I see it. https://github.com/Ichoran/scala-collections-laws/tree/refactor-with-sourcecode

**Comment by Ichoran** [comment]
I didn't want to just swap out the main branch without telling anyone, and I ran out of time to make plans to switch "officially".

**Comment by Ichoran** [comment]
collections-laws are now implemented reasonably well, albeit in a bit of an add-hoc way at

 https://github.com/Ichoran/scala-collections-laws/tree/add-strawman-coll

Note that you have to, right now, manually drop the strawman and sourcecode jars into the two folders.  (I take forever to get sbt to do anything smart, which I didn't think was a good use of limited time.)

I am translating the issues I've found into the issue tracker.  I think this resolves this issue, though one could ask for targeted coverage of particular things as a follow-up.

(Also, for the dual support for old and new collections to be dropped, and for collections-laws to just support the new collections.)

**Comment by julienrf** [comment]
This is great @Ichoran! How do we know which collection types are tested?
