### ISSUE TITLE
Provide default implementations of factory methods when possible

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#335]
The `fromSpecificIterable`, `newSpecificBuilder`, and other factory methods that are currently implemented in concrete collections only could probably have default implementations earlier in the hierarchy.

**Comment by julienrf** [comment]
In #379, @lrytz wrote the following:

In 2.12:

```
scala>   class K extends Iterable[Int] {
     |     var x = 10
     |     def iterator: Iterator[Int] = new Iterator[Int] {
     |       def hasNext = x > 0
     |       def next() = { x -= 1; x}
     |     }
     |   }
defined class K

scala>

scala> (new K).toList
res0: List[Int] = List(9, 8, 7, 6, 5, 4, 3, 2, 1, 0)
```

In strawman I need to add

```
    def iterableFactory: collection.IterableFactoryLike[Iterable] = Iterable
    protected[this] def fromSpecificIterable(coll: scala.Iterable[Int]): Iterable[Int] = iterableFactory.from(coll)
    protected[this] def newSpecificBuilder(): collection.mutable.Builder[Int, Iterable[Int]] = iterableFactory.newBuilder()
```

It's pretty mechanical (and also not obvious to newcomers) in the basic case when you don't need specific return types for operations. Should we provide some helper classes with default implementations?

**Comment by szeiger** [comment]
The approach I had in mind runs into a bug (or a more fundamental language problem?) in Scala (but would work in Dotty): https://github.com/scala/bug/issues/10725
