### ISSUE TITLE
Consider adding a replace operation to Seq

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#339]
We already have it for `String`: `"foo".replace('o', 'e') == "fee"` but we could generalize to `Seq`.

Possible default implementation:

~~~ scala
trait SeqOps[+A, +CC[_], +C] {

  def replace[B >: A](elem: B, replaced: B): CC[B] =
    map(a => if (a == elem) replaced else a)

}
~~~

**Comment by kubukoz** [comment]
I think I could try implementing this. I'll need a moment to get familiar with the codebase though :)

**Comment by martijnhoekstra** [comment]
Is there a reason to prefer `replaced: B` over `replaced: A`? Do you really want to call `List(1, 2, 3).replace("foo", "bar")`?

**Comment by odd** [comment]
@martijnhoekstra Hmm, don't you mean `elem: A` rather than `replaced: A`? 
```scala
trait SeqOps[+A, +CC[_], +C] {
  def replace[B >: A](elem: A, replaced: B): CC[B] =
    map(a => if (a == elem) replaced else a)
}
```
Unfortunately neither `elem` nor `replaced` can be of type `A` since that would put a covariant type in a contravariant position (`A` is defined as `+A` in `SeqOps`).

@julienrf On a different note, shouldn't `replaced` rather be called `replacement`?

**Comment by julienrf** [comment]
I think the method should be named `replaced` (past tense) and the replacement value should be named `replacement`, indeed @odd.

**Comment by kubukoz** [comment]
Apparently @purijatin is working on this ;)

**Comment by kubukoz** [comment]
WDYT about adding a `replacedOnce` (or something like that)` variant? I'm aware that `updated` exists, but it takes an index, whereas I can imagine a common usecase being `replace(indexOf(...), with)`.

**Comment by NthPortal** [comment]
Is there anywhere it should be overridden for performance?

**Comment by szeiger** [comment]
Both the implementation in contrib and the open PR https://github.com/scala/scala/pull/6752 make me question the utility of this method as they only provide a default implementation with a simple translation to `map`. Are there any Seq types that would allow a more efficient implementation (which could not be generalized to `map`)?
