### ISSUE TITLE
Recommended way to produce collections

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#34]
What’s the recommended way to produce collections?

The default collections are immutable collections. When we [present](https://www.scala-exercises.org/scala_tutorial/standard_library) how to use them we mention the `::` operator (for `List`) to construct a new collection. Constructing a `List` containing the n first fibonacci numbers would then look like this:

~~~ scala
def fibonacci(n: Int): List[Int] = {
  def loop(remaining: Int, prev: Int, prevPrev: Int, result: List[Int]): List[Int] =
    if (remaining > 0) {
      val value = prev + prevPrev
      loop(remaining - 1, value, prev, value :: result)
    } else result
  loop(n - 2, 1, 0, List(1, 0)).reverse
}
~~~

But then one might ask: would it be possible to construct the sequence in the right order from the beginning?

One way to do that is to use `Builder`s:

~~~ scala
def fibonacci(n: Int): List[Int] = {
  val builder = List.newBuilder[Int]
  builder += 0
  builder += 1
  def loop(remaining: Int, prev: Int, prevPrev: Int): Unit = {
    if (remaining > 0) {
      val value = prev + prevPrev
      builder += value
      loop(remaining - 1, value, prev)
    } else ()
  }
  loop(n - 2, 1, 0)
  builder.result()
}
~~~

But then mixing immutable and mutable programming style feels a bit awkward… We could go all mutable but then that would contrast with the general advice of going immutable first.

We can consider several alternative solutions, like having an immutable `Tsil` that would append elements instead of prepending them, but then the resulting collection would require precautions (e.g. we should avoid to use head/tail decomposition on it).

Otherwise, we could use a collection implementation that provides good performance for both `+:` and `:+`, like `Vector`. But that seems perfectible…

I think that it would be great to provide a general API to efficiently construct all kind of collections. The user-facing API would use immutable style, but the underlying implementation would use specific mutable collections (e.g. `ListBuffer` to build a `List`, etc.).

It seems that what I am looking for are “unfolds”, but I’m wondering if people tried other alternatives or have any advice to address this problem? Does someone know a nice implementation of unfolds? (I mean, a lot of variants could make sense: should we discard the final state or not? should we support the production of several elements in a single step? conversely, should we support not producing an element yet without stopping the process? etc.)

**Comment by odersky** [comment]
I usually use a `ListBuffer` as an accumulator, like this:
   
    def fibonacci(n: Int): List[Int] = {
      def loop(remaining: Int, prev: Int, prevPrev: Int, buf: ListBuffer[Int]): ListBuffer[Int] =
        if (remaining > 0) {
          val value = prev + prevPrev
          loop(remaining - 1, value, prev, buf += value)
        } else buf.toList
      loop(n - 2, 1, 0, ListBuffer(0, 1))
    }

It's "purely functional" code, but with a mutable type used linearly.

**Comment by julienrf** [comment]
Also, just to get a comparison basis, here is what an unfold based version could look like:

~~~ scala
def fibonacci(n: Int): List[Int] =
  List(0, 1) ++ List.unfold((n, 0, 1)) {
    case (0, _, _) => None
    case (n, prevPrev, prev) =>
      val value = prevPrev + prev
      Some(value -> (n - 1, prev, value))
  }
~~~

The nice thing is that we don’t have to manage the loop and the accumulator by ourselves.

**Comment by ivanopagano** [comment]
I like the unfolding approach, for its declarative approach.
So every concrete collection should provide an implementation of something similar to the following? (code simplified, no type parameter bounds were hurt for this example)
```
trait Unfolder[COLL[_]] {
  def unfold[A, B](seed: A)(f: (A) ⇒ Option[(B, A)]): COLL[B]
}
```
Is there any "traditional" collection type which would not fit with this approach?

**Comment by julienrf** [comment]
I think an *unfold* library could be implemented separately.
