### ISSUE TITLE
Port immutable.Queue

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#341]
We currently have no equivalent of `collection.immutable.Queue`. An easy way to fix that would be to simply port the existing implementation. Or we could use #88 which has “ O(1) `enqueue` and amortized O(1) `dequeue`, but it also has O(1) `++` and O(1) `push`”

**Comment by Ichoran** [comment]
What's the constant factor on `Steque`?  If it's comparable to bare `Queue`, we can just replace the `Queue` implementation with this (and we get a decent deque for free).  If it is substantially slower at core queue operations, then we could at it as well (probably as `Deque`, since that is probably why you would want it instead of `Queue`).

**Comment by joroKr21** [comment]
AFAIK it's not a full `Deque` as it supports efficient `enqueue`  at bot ends, but efficient `dequeue` only at one end. Still a useful collection to have :+1:

**Comment by Ichoran** [comment]
Amortized O(1) can still be efficient, but anyway, I forget the performance characteristics, and for a core collection replacement, those are really important.  (Especially since an improvement over `Vector` is the only reason to use `Queue`.)

**Comment by edmundnoble** [comment]
The constant factor on enqueue and dequeue is just a single constructor call. All folds are implemented with a tight loop operating on an ArrayBuffer; I have benchmarks comparing the Queue and Steque implementations at https://github.com/edmundnoble/scabsbench but I haven't run them in a while, and the results aren't up.

**Comment by Ichoran** [comment]
The .steq numbers there (in latest_results) look amazingly worse than everything else.  I haven't dug any deeper but something must be amiss.

**Comment by edmundnoble** [comment]
Er you should be looking at the .cat numbers, sorry :)

**Comment by edmundnoble** [comment]
Those results, also... not the latest.

**Comment by Ichoran** [comment]
Ah, those look quite promising.

**Comment by edmundnoble** [comment]
Thanks, they can also be tuned; the arraybuffer could be a bit bigger.

**Comment by julienrf** [comment]
Fixed by 91fbf408fc7a25848108add55227f8d5508def88
