### ISSUE TITLE
“prepend” in mutable.Buffer is confusing

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#359]
In `collection.mutable.Buffer`, we have:

~~~ scala
def prepend(elem: A): this.type
def +=: (elem: A): this.type = prepend(elem)
~~~

- the name “prepend“ is very close to the inherited `prepended` operation,
- all other expansion operations come in two variants: one that operate on a single element (e.g. `prepended`, `addOne` and `subtractOne`) and one that operates on a collection of elements (e.g. `prependedAll`, `addAll` and `subtractAll`), but there is no `prependAll` in `Buffer` (it exists in 2.12 so we should add it for the sake of compatibility anyway),
- the symbolic alias for `prepend` is confusing: it mutates the object on the right-hand side of the `=` (`foo +=: bar` prepends `foo` into the `bar` collection)

I think we should:

- Add `prependAll`,
- Deprecate the symbolic alias for `prepend` because I find it confusing to . Also, there is a comment in the source code saying that we should not have `+=:` and `++=:`, what was the reason for that? (@Ichoran maybe you know?)
- maybe find a new name for `prepend` and `prependAll`, to avoid the proximity with `prepended` and `prependedAll`, which return a new collection instead of modifying it?

**Comment by Ichoran** [comment]
Don't we always have the plain vs. `ed` problem, e.g. with `append` and `update`?  This isn't any different is it?

I am not aware of what the logic behind dropping `+=:` and `++=:` is.  Maybe it's the "symbol soup" factor, or maybe because it is easy to confuse with `+:` and `++:`, which give the same return type, but where confusing the two is very unlikely to give correct code.

**Comment by julienrf** [comment]
`append` is deprecated in favor of `addOne`. The problem exists for `update`/`updated`, though, you’re right.

**Comment by szeiger** [comment]
Sequences have `append` and `prepend` (plus `*All` versions and symbolic aliases). `addOne` is inherited from `Growable` where no sequential order can be assumed. I think the right course of action is to un-deprecate `append`. It makes sense for sequences to have symmetrical `append` and `prepend`. `+=` is actually an alias for `addOne`, not for `append`. This blurs the distinction between ordered and unordered append but that can be solved by requiring that `addOne` and `append` are the same for `Seq`.

We have similar cases with `concat` (which should be the same as `appendAll` for `Seq`) and `size` (which should be the same as `length` for `Seq`).
