### ISSUE TITLE
Consider adding a deprecated `+` on collection.Set/Map

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#375]
The fact that `collection.Set` and `mutable.Set` no longer have a `+` method can lead to very error confusing messages or even confusing compiling code. I think this could cause quite some headaches for users during the migration.

```
scala> Set(1) + 2
                ^
       error: type mismatch;
        found   : Int(2)
        required: String
```

User: It's clearly a set of `Int`s, why does it want a `String`?

```
scala> Set("a") + "b"
res14: String = HashSet(a)b
```

User: Going to file a bug, there's something wrong with `HashSet.toString`.

Same for Map (`Map(1 -> "a") + (2 -> "b")`).

One could argue we have similar issues with 2.12 collections, for example
```
scala> List(1) + 2
<console>:15: error: type mismatch;
 found   : Int(2)
 required: String
       List(1) + 2
                 ^

scala> List("a") + "b"
res10: String = List(a)b
```

But the difference is, IMO, that `+` is a common operation on (immutable) Sets and Maps, but not on other types. So it will happen more often that someone will try to call `+` on a `collection.Set/Map`.

**Comment by lrytz** [comment]
(It took me a while to figure out that this is what's going on when adapting the test here: https://github.com/scala/scala/blob/2.13.x/test/files/run/colltest1.scala#L140-L143)

**Comment by lrytz** [comment]
What's even more confusing is that there's a `++` method on `collection.Set` (and therefore `mutable`) which clones.

**Comment by lrytz** [comment]
Even if we didn't have `any2stringadd`, I'd be for adding `+` to improve compatibility.

We should also discourage the use of `collection.X` factories. Or is there a good reason to ever use `collection.Set("hi")` over `collection.immutable.Set("hi")`?

**Comment by lrytz** [comment]
This was fixed in https://github.com/scala/collection-strawman/commit/87b27654d4a5bc811ec957114316f8c596733ec1

**Comment by SethTisue** [comment]
(most people watching this repo probably already know this, but note that https://github.com/scala/scala/pull/6315 deprecates (though does not yet remove) `any2stringadd` and we expect to merge it for 2.13.0-M4 afaik)
