### ISSUE TITLE
immutable.HashSet.subsetOf should not invoke hashCode

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#380]
This test fails: https://github.com/scala/scala/blob/2.13.x/test/files/run/t7326.scala#L45-L61
Added in https://github.com/scala/scala/pull/3315

**Comment by julienrf** [comment]
It looks like I omitted to copy the implementation of `subsetOf` for no good reason…
https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/immutable/HashSet.scala#L74
