### ISSUE TITLE
Mismatching signature of copyToArray

### ISSUE THREAD

**Issue by Ichoran** [scala/collection-strawman#397]
The old collections have a `copyToArray` that takes two numeric parameters; the second one is the maximum number of elements to copy.  The new version is missing the second parameter.

```
List(1, 2, 3).copyToArray(new Array[Int](2), 1, 1)
```
should compile.

**Comment by jiminhsieh** [comment]
If no one work on this one, I will try to give this a shot. :)

**Comment by julienrf** [comment]
@jiminhsieh please go ahead!

**Comment by julienrf** [comment]
Fixed by #452.
