### ISSUE TITLE
Maps with special keys (AnyRefMap and LongMap) cannot map/flatMap etc

### ISSUE THREAD

**Issue by Ichoran** [scala/collection-strawman#403]
The four operations `map`, `flatMap`, `++`, and `collect` cannot be used with `AnyRefMap` or `LongMap` and still produce a map of the appropriate type.  This is _not_ just a compile-time issue for `map`, `flatMap` and `collect`; the map is actually made as a generic `HashMap` even if the element types are okay.  With `++`, the map type is preserved, but the compiler forgets what it is and calls it a generic `mutable.Map`.

This should be improved if possible, as these are all really basic operations and having them essentially "not work" significantly limits the usability of the maps with special keys.

**Comment by julienrf** [comment]
IIUC the fix is to add overloads of the `map`, `flatMap`, `++` and `collect` operations.
