### ISSUE TITLE
Semantics of zip on maps has changed

### ISSUE THREAD

**Issue by Ichoran** [scala/collection-strawman#404]
With previous collections zipping maps to each other (or a map to anything) would create a new map whose keys were the (key, value) pairs from the old map, and whose values were whatever was zipped to on the right.

Now, `zip` returns an `ArrayBuffer` typed as an `Iterable` instead when maps are zipped together.

We should we be sure that we want to not keep the old behavior.  (It was a bit peculiar, admittedly, but an unexpected change may well be worse.)

**Comment by julienrf** [comment]
I think the new behavior is more intuitive, but we should document that breaking change in the FAQ.

**Comment by julienrf** [comment]
Done.
