### ISSUE TITLE
Consider fallback to sorted set type for BitSet

### ISSUE THREAD

**Issue by Ichoran** [scala/collection-strawman#405]
BitSet can only be mapped if the output is also an integer; otherwise there's an ambiguous reference between StrictOptimizedIterableOps and SortedSetOps.  It's easy to pick the former with `unsorted`.  But the latter doesn't seem to have any easy way to select.  It should either be the default, if possible, or have a method that would upcast to a generic sorted set type (if there is a method name that seems obvious enough)

**Comment by ruhly** [comment]
It appears the same ambiguous reference issue exists with `flatMap`, `collect`, and `zip` as well?

**Comment by szeiger** [comment]
This appears to be already resolved. The test case from #500 works in master without the explicit `toSortedSet` call.
