### ISSUE TITLE
`takeWhileInPlace` overshoots bounds

### ISSUE THREAD

**Issue by Ichoran** [scala/collection-strawman#406]
```
ArrayBuffer(true, false).takeWhileInPlace(_ == true)
```

throws an out of bounds exception (as do all the mutable sequences).

(`ListBuffer` also throws an index out of bounds exception--should check to make sure this is working efficiently.)

**Comment by Ichoran** [comment]
Fix #409 first--this one is probably a consequence of that?

**Comment by marcelocenerine** [comment]
Yes indeed.

**Comment by julienrf** [comment]
Fixed by #423.
