### ISSUE TITLE
patchInPlace throws a class cast exception

### ISSUE THREAD

**Issue by Ichoran** [scala/collection-strawman#407]
```
java.lang.ClassCastException: strawman.collection.immutable.Nil$ cannot be cast to strawman.collection.immutable.$colon$colon
strawman.collection.mutable.ListBuffer.locate(ListBuffer.scala:153)
strawman.collection.mutable.ListBuffer.patchInPlace(ListBuffer.scala:272)
```

The call was to `ArrayBuffer.empty[Int].patch(-1, ArrayBuffer.empty[Int], -1)`, but this shouldn't happen regardless.

**Comment by marcelocenerine** [comment]
The call must have been `ListBuffer.empty[Int].patchInPlace(-1, ListBuffer.empty[Int], -1)`. This is probably caused by the fact that the `from` parameter is not normalized.
