### ISSUE TITLE
Mutable maps and sets don't mapInPlace properly

### ISSUE THREAD

**Issue by Ichoran** [scala/collection-strawman#408]
They end up behaving like `xs ++= xs.map(f)` instead of `xs = xs.map(f)`.

Example code:

```
val xs = mutable.HashSet(1)
xs.mapInPlace(_ + 1)
xs
```

xs is now `Set(1, 2)`

**Comment by optician** [comment]
It seems issue already have been fixed. Scala project, branch 2.13.x-new-collections.
```
[2.13.x-new-collections] root: console
[info] Starting scala interpreter...
[info]
Welcome to Scala 2.13.0-M4-pre-20d3c21 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

import scala.collection._
val xs = mutable.HashSet(1)
xs.mapInPlace(_ + 1)
xs

// Exiting paste mode, now interpreting.

import scala.collection._
xs: scala.collection.mutable.HashSet[Int] = HashSet(2)
```

**Comment by optician** [comment]
Tests exist already.
https://github.com/scala/scala/blob/2.13.x/test/junit/scala/collection/mutable/HashSetTest.scala#L39
https://github.com/scala/scala/blob/2.13.x/test/junit/scala/collection/mutable/HashMapTest.scala#L52

**Comment by julienrf** [comment]
Thanks @optician to have double checked that! I’m closing the issue.
