### ISSUE TITLE
dropInPlace and dropRightInPlace are unsafe

### ISSUE THREAD

**Issue by Ichoran** [scala/collection-strawman#410]
They should mimic the behavior of `drop` and `dropRight`, where elements beyond the end of the collection (or negative numbers of elements) are ignored.  Presently, an IndexOutOfBoundsException is thrown instead.

Sample code:

```
ArrayBuffer(1, 2).dropRightInPlace(4)
ArrayBuffer(1, 2).dropInPlace(4)
```

These should both clear out the `ArrayBuffer`.  (`ArrayBuffer` is not the only class affected.)

**Comment by julienrf** [comment]
Fixed by #423.
