### ISSUE TITLE
flatMapInPlace ignores all but the last collection

### ISSUE THREAD

**Issue by Ichoran** [scala/collection-strawman#412]
```
val xs = ListBuffer(3, 4, 5)
val ys = List(-1, -2, -3, -4, -5, -6)
xs.flatMapInPlace(i => ys take i)
xs
```
should yield `ListBuffer(-1, -2, -3, -1, -2, -3, -4, -1, -2, -3, -4, -5)`.  Instead it yields `ListBuffer(-1, -2, -3, -4, -5)`.

(You can distinguish "last one" from "longest one" by switching `take` to `drop`.)

**Comment by marcelocenerine** [comment]
`ArrayBuffer.flatMapInPlace ` is also buggy:

```
val xs = ArrayBuffer(3, 4, 5)
val ys = List(-1, -2, -3, -4, -5, -6)
xs.flatMapInPlace(i => ys take i)
xs
```
yields
`res2: strawman.collection.mutable.ArrayBuffer[Int] = ArrayBuffer()`
