### ISSUE TITLE
Harmonize use of `@SerialVersionUID`

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#418]
There won't be any serialization compatibility between 2.12 and 2.13 collections, so we should make sure to use `@SerialVersionUID` numbers different than in 2.12. Other than that, we can pick any number - there's no advantage in picking the number computed by `serialver`.

So I propose we just use `@SerialVersionUID(3L)` across the entire 2.13 collections (there are some uses of `1L` and `2L` in 2.12 collections).

See also https://github.com/scala/scala-dev/issues/237

**Comment by julienrf** [comment]
Fixed by #444.
