### ISSUE TITLE
A more sensible `groupBy` API?

### ISSUE THREAD

**Issue by LPTK** [scala/collection-strawman#42]
This is the result of some personal experimentations. Please let me know if it's not appropriate to post that here.

## Introduction

The `groupBy` method is very powerful and pretty useful, but it often suffers from inefficiencies because of the way its API is specified:
 
 * It is supposed to return an immutable `Map`. While sometimes useful, it's often not what one needs. Many uses of `groupBy` end up mapping or simply iterating on the result, in which case having a `Map` early is counter-productive.
 Notice that the [standard implementation](https://github.com/scala/scala/blob/44971d104f4364a0ddaa4f05afc4cc61ee39cdf7/src/library/scala/collection/TraversableLike.scala#L318-L330) of `groupBy` constructs a `mutable.Map` _and then_ rebuilds it into an `immutable.Map`, a final step that is often redundant.
 **Proposal:** Make the method return an `Iterable` of the same type as the current collection, and let the user decide whether to call `toMap` on it or not. One can also write something like `xs.view.groupBy(f)` which returns an immutable view into the internal `mutable.Map` used by `groupBy`, avoiding any unnecessary intermediate container (note that the call to `groupBy` is still strict nonetheless).
 
 
 * A very common use-case of `groupBy` involves transforming the values after having grouped them. Doing this as a second step as in `xs.groupBy(_.a).mapValues(_.map(_.b))` is wasteful as it creates needless intermediate collections.
 **Proposal:** Have an optional parameter to specify the value mapping to perform while grouping values. As long as this parameter has a default value, it should not even break the current API, as both `groupBy(f)` and `groupBy(f,g)` would be valid.
 Note: after implementing this, I discovered that user @balefrost [had already mentioned the problem](https://github.com/lampepfl/dotty/issues/818#issuecomment-157086673), and that it turns out that's how it's already done in C#.
  
 * With the new design based on the `Iterable` hierarchy, it is currently not possible to directly build the buckets of the grouped elements because there is no way to obtain a builder of the current collection. Although [it should be possible eventually](https://gitter.im/scala/collection-strawman?at=58b96c06e961e53c7f942c71), I'm not even sure it makes much sense to have the buckets mirror the original collection type anyway. In this proposal `groupBy` simply returns buckets as `View[V]`.
 
## Implementation

I have implemented the traditional `groupBy` API (but it's currently suboptimal because of the lack of `newBuilder`), along with my proposal for a modified API called `viewBy`, the signature of which is:

```scala
def viewBy[K,V](fk: A => K, fv: A => V = (a:A) => a): C[(K, View[V])]
```

## Benchmark

To show an example where one only wants to iterate over the result of `groupBy`, I implemented the following equivalent algorithms (where `xs:Iterable[(Int,java.lang.String)]`):

```scala
def groupBy(): Any = {
  var sum = 0
  xs.groupBy(_._1).mapValues(_.map(_._2)).foreach {
    case (k,v) => sum += k * v.foldLeft(0)(_ + _.length)
  }}
def groupBy_sensible(): Any = {
  var sum = 0
  xs.viewBy(_._1,_._2).foreach {
    case (k,v) => sum += k * v.foldLeft(0)(_ + _.length)
  }}
def groupBy_sensView(): Any = {
  var sum = 0
  xs.view.viewBy(_._1,_._2).foreach {
    case (k,v) => sum += k * v.foldLeft(0)(_ + _.length)
  }}
```

My results are as follows:

![groupby](https://cloud.githubusercontent.com/assets/2545083/23658665/b80001b2-0343-11e7-8e9f-feacb5634f4d.png)

`groupBy_sensible` and `groupBy_sensView` are often significantly faster than the other implementations, up to twice faster for smaller collections.

**Comment by DarkDimius** [comment]
While considering the same question in ScalaBlitz,
we've decided to implement this:

```
def groupMapAggregate[K, M](gr: T => K)(mp: T => M)(aggr: (M, M) => M)
```

It subsumes all the use-cases that you've presented and allows to implement them efficiently

**Comment by LPTK** [comment]
@DarkDimius I suspect that would be less performant in the cases where you want to aggregate the groups into iterables. In your example you have to map the values to singleton vectors (or lists or whatever) and then merge the vectors. Wouldn't that incur significant overhead as compared to simply growing a buffer (as in the implementation of `viewBy`)?

**Comment by DarkDimius** [comment]
@LPTK 
The underlying implementation used a novel datastructure invented by @axel22, that, to the best of my knowledge, wasn't published. We didn't see a significant overhead compared to creating a vector.

**Comment by LPTK** [comment]
It also does not seem to solve the first point, which is to avoid creating an unnecessary map at the end. (Although I can see the benefit of that approach in the context of parallel collections – which have probably very different characteristics.)

> We didn't see a significant overhead compared to creating a vector

By `creating a vector`, do you mean growing a buffer (which is what I propose)?

**Comment by DarkDimius** [comment]
> By creating a vector, do you mean growing a buffer (which is what I propose)?

It depends on how you grow the buffer, so I've specified a specific way to do it to be more precise.

**Comment by julienrf** [comment]
I think the three signatures all make sense. I would go with the following methods:

~~~ scala
trait IterableMonoTransforms[A, Repr] {
  // similar to the current one
  def groupBy[B](f: A => B): collection.Map[B, Repr]
}

trait IterablePolyTransforms[A, CC[X]] {
  // equivalent to groupBy(f).mapValues(_.map(g)) but more efficient
  def groupAndMap[B, C](f: A => B)(g: B => C): collection.Map[A, CC[C]]
}

trait IterableOps[A] {
  // equivalent to groupBy(f).mapValues(_.map(g).reduce(h)) but more efficient
  def groupAndReduce[B, C](f: A => B)(g: B => C)(h: (C, C) => C): collection.Map[A, C]
}
~~~

I don’t have a strong opinion on the result type. I think returning a bare `collection.Map` should be what is expected in most of the case and would still allow us to implement it efficiently (ie no conversion to an immutable `Map`).

What do you think?

**Comment by axel22** [comment]
@LPTK @DarkDimius  https://axel22.github.io/resources/docs/lcpc-conc-trees.pdf

**Comment by DarkDimius** [comment]
@julienrf 
I'm not sure if we should have all three.
note that 
`groupMapAndReduce` is as efficient to implement as the other two but is more expressive, subsuming `groupBy` and `groupAndMap` themselves.

**Comment by julienrf** [comment]
As a user most of the time I want `groupAndMap`. I think it is probably easier, conceptually, to have a method that just does that and does not take a third parameter that I don’t care about.

**Comment by DarkDimius** [comment]
@axel22, glad to see it was published!

**Comment by LPTK** [comment]
@julienrf why not merge `groupBy` and `groupAndMap`? As I said, with an optional argument, it would not break the API. Would there be a performance difference?

@DarkDimius I'd really like to see an implementation of `groupMapAndReduce` that demonstrates matching performance with `groupAndMap` on sequential collections.
Also notice that you push the collection-building onto the user with this interface. Users might not want to write `groupAndMapReduce(f)(g andThen (SomeCollection apply _))(_ ++ _)` instead of just `groupAndMap(f)(g)`, especially since they might not be aware of the fact they should be using @axel22's awesome data structure in order to have acceptable performances.

**Comment by lihaoyi** [comment]
For what it's worth, I'd call them `groupMap` and `groupMapReduce`, leaving out the `And`; conciseness matters, and `And` doesn't really provide any more information to a user of this API than leaving it out

**Comment by julienrf** [comment]
The discussion is a bit complex to follow, so here is a summary of the API that I think we should implement:

~~~ scala
trait IterableOps[A, CC[_], C] {
  // the current one (already implemented)
  def groupBy[K](f: A => K): Map[K, C]

  // equivalent to groupBy(f).mapValues(_.map(g)) but more efficient
  def groupMap[K, B](f: A => K)(g: A => B): Map[K, CC[B]]

  // equivalent to groupBy(f).mapValues(_.map(g).reduce(h)) but more efficient
  def groupMapReduce[K, B](f: A => K)(g: A => B)(h: (B, B) => B): Map[K, B]
}
~~~
