### ISSUE TITLE
Consider adding `intersects` operation to sets

### ISSUE THREAD

**Issue by buzden** [scala/collection-strawman#426]
Aren't there any objections to having an operation `intersects` for sets

- with meaning `xs.intersect(ys).nonEmpty` or `xs.exists(ys)` (where `xs` and `ys` are sets);
- that can be implemented in more optimal way in some cases, e.g. for `BitSet`s or `HashSet`s;
- which is more readable and semantically clear: compare `xs intersects ys` to `xs exists ys` or `xs.intersect(ys).nonEmpty`

**Comment by Ichoran** [comment]
I find this significantly less clear because it looks too much like you're creating a new set, not a `Boolean`.

**Comment by SethTisue** [comment]
these things look appealing considered individually, but considered collectively, you end up with an overwhelming amount of methods — arguably we're at or past that point already

**Comment by ShaneDelmore** [comment]
For an alternative point of view I found it very clear, I’ve never had call to use either but upon first reading I assumed xs intersect ys produced the intersection and xs intersects ys returned a boolean based on the names.  I read intersect as an action, and intersects as a question.

**Comment by alex1712** [comment]
Hello, I am trying to collaborate for first time.

I thought this could be an easy start. As I understand by the comments the final decision would be to implement it as `xs intesects ys` returning a boolean if any of the element is present in both sets.

I would think of implementing this in scala.collection.SetOps. Maybe I am too optimistic here, but this change should be a one line change there.

I would be happy to hear your opinions :)

Thanks in advance

**Comment by buzden** [comment]
> I would think of implementing this in scala.collection.SetOps. Maybe I am too optimistic here, but this change should be a one line change there.

In ``SetOps`` it looks really simple, yes.

But it can be implemented in much more effective way in special set implementations like ``TreeSet``.

**Comment by alex1712** [comment]
I might be completely wrong, but if I implement it as following:
```
  def intersects(that: Set[A]): Boolean = this.exists(that.contains)
```
and as the `contains` method is in `TreeSet` wouldn't that be enough?

**Comment by buzden** [comment]
Well, generally you can implement ``intersects`` without any knowledge of internals of sets both as ``this exists that`` and ``that exists this`` (``this exists that`` is a short form for ``this.exists(that.apply)``, which is equivalent to your ``this.exists(that.contains)`` for ``Set``s).

Not knowing how iteration and ``exists`` method is implemented, we can bound computation time approximately as _n_ multiplied with effectiveness of lookup of function passed to the ``exists``.

``TreeSet`` have _log n_ lookup, thus is means that generally for them it may be better to implement ``intersects`` as ``that exists this`` and not as ``this exists that``.

I'm not touching here ability to take sizes into account sometimes (this may not work when size is not cheap to count).

**Comment by buzden** [comment]
Moreover, it seems that we can implement _linear_ overloaded implementation, e.g. for `SortedSet`s (i.e. those one in `SortedSetOps` that accepts another `SortedSet` as its argument)

**Comment by alex1712** [comment]
As I check TreeSet `size` method has a O(1) complexity, so I could add a check to use `that` as left side when `this` is bigger than `that`.  With the assumption that `exists` will have always a bigger complexity as the lookup of `contains`. 

Makes sense?

**Comment by buzden** [comment]
> Makes sense?

Looks so.

**Comment by SethTisue** [comment]
I still lean towards _not_ adding this. Am I an outlier?

**Comment by alex1712** [comment]
For me is no problem not merging it, I thought, as it had the tag for the next Milestone, that it was decided to put it in. 

Feel free to discard the PR it you think it is too much for the standard library. This PR helped me to start collaborating anyway :)

Thanks

**Comment by SethTisue** [comment]
thanks @alex1712 for your understanding
