### ISSUE TITLE
Overloading resolution with constrained types

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#432]
```
scala> def f[T](a: Array[T]) = a.map(x => x)
                                    ^
       error: No ClassTag available for T
```

The problem is that there are two overloads
  - `def map[B](f: A => B): CC[B]` (in `StrictOptimizedIterableOps`)
  - `map[B: ClassTag](f: A => B): Array[B]` (in `ArrayOps`)

2.12 would pick the generic version when there's no `ClassTag` in scope. A workaround is to have an expected type:

```
scala> def f[T](a: Array[T]): collection.Seq[T] = a.map(x => x)
f: [T](a: Array[T])Seq[T]
```

Stefan on gitter: "That's probably unavoidable given the way overload resolution works. We can't produce different results based on the presence or absence of some implicit evidence anymore like we could with CanBuildFrom"

Same issue with other constrained types, for example sorted sets. In comprehensions the error message is very unhelpful.

```
scala> def f[T](a: collection.immutable.TreeSet[T]) = a.map(x => x)
                                                           ^
       error: No implicit Ordering defined for T.

scala> def f[T](a: collection.immutable.TreeSet[T]) = for (x <- a) yield x
                                                             ^
       error: No implicit Ordering defined for T.
```

Let's think a bit more how we can improve here.

**Comment by julienrf** [comment]
In my opinion this is a feature, and the error message is not that bad. Maybe a better message would be: “you need an implicit `ClassTag[T]` to build an `Array[T]`. Either get such an implicit value or transform your `Array[T]` into a different type of sequence.”. And, for sorted sets: “you need an implicit `Ordering[T]` to build a `SortedSet[T]`. Either get such an implicit value or upcast your `SortedSet[T] into a `Set[T]` with the `unsorted` method”. I don’t think we can produce such messages without hardcoding them in the compiler, though :(

**Comment by julienrf** [comment]
If we could add `@implicitNotFound` annotation *at use site* that could solve the issue:

~~~ scala
trait SortedSet[A] {
  def map[B](f: A => B)(implicit o: Ordering[B] @implicitNotFound("you need an implicit Ordering[T] to build a SortedSet[T]. Either get such an implicit value or upcast your SortedSet[T] into aSet[T]with theunsorted` method."))
}
~~~

**Comment by lrytz** [comment]
That's a great idea!

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6809
