### ISSUE TITLE
Extension Methods without CanBuildFrom?

### ISSUE THREAD

**Issue by dlwh** [scala/collection-strawman#44]
(Maybe I'm late to the party on this. I've been a bit checked out from mailing lists and such. Sorry if so!)

I'm curious about the future of ergonomic generic extension methods in the new collections library, at least if `CanBuildFrom` is removed entirely.

For instance, in our codebase, we've introduced a method `flatCollect`, which we frequently find useful. (I noticed `collect`'s missing, I assume that's just because it's relatively uninteresting, in terms of design.) It has the obvious meaning, with signature:

```scala
def flatCollect[Result, B](f: PartialFunction[A, TraversableOnce[B]])
                              (implicit cbf: CanBuildFrom[Coll, B, Result]): Result 
```

We also have `toMultiMap`, which is an efficient implementation of `xs.groupBy(_.a).eagerMapValues(_.map(_.b))` (as mentioned in #42 but using our own `eagerMapValues` because of frequent unintended consequences of the lazy variant).

```scala
implicit class ScEnrichColl[Coll <: Traversable[_], A, B](val __this: Coll)(implicit view: Coll <:< Traversable[(A, B)]) {
  def toMultiMap[Result](implicit cbf: CanBuildFrom[Coll, B, Result]): Map[A, Result] = ???
}
```

Maybe I'm being insufficiently imaginative, but it's hard for me to see how to implement them in the new approach where they maintain the same level of ergonomics as before. It's possible it's worth the reduction in complexity, but it makes me somewhat sad.

One answer is "use views and use `to`/`FromIterable`" at the end, but I don't think that handles the `toMultiMap` case particularly nicely. Another is to have `CBF`, but only for these cases. (This can be largely done via an external library, possibly.) Is there another?

**Comment by dlwh** [comment]
Basically, what's sad about this is that you lose the ability to extract methods for common patterns like `toMultiMap`, without giving up the more precise types. You can do toMultiMap(_: FromIterable[B]), of course, but:

1. the API is a bit less fluent (imho), and
2. that implementation of toMultiMap I think *has* to make unnecessary intermediates that would not be required using CBF.

**Comment by julienrf** [comment]
In the current state, this kind of use of `CanBuildFrom` would be replaced by an implicit `Builder` factory, as in [this example](https://github.com/scala/collection-strawman/blob/d3b1d42673f2914bebfe75a68c7e7ef15bf5bfc3/src/test/scala/strawman/collection/test/TraverseTest.scala#L15-L19).

The limitation is that we can not define a `flatCollect` method that is polymorphic over the *kind* of the collection type constructor (said otherwise, you can not write a single `flatCollect` method that works both with `Map[_, _]` and `List[_]`).

**Comment by julienrf** [comment]
Maybe this kind of use cases would justify to introduce a `CanBuild[-A, +Repr]` thing.

**Comment by LPTK** [comment]
@julienrf what would be the difference between this `CanBuild[-A, +Repr]` and the current `Builder[-A, +To]` in terms of API?

I also have similar facilities that rely on CBF. For example:

```scala
def mapSplit[B,C,Left,Right](f: A => Either[B,C])
                            (implicit bfLeft:  CanBuildFrom[Repr, B, Left],
                                      bfRight: CanBuildFrom[Repr, C, Right]): (Left, Right)
```

I knew it worked with things like `String` (producing `String`s), but I did not even realize that it also worked with `Map` types... Now I'm even more impressed with the old design 😅 

But however technically impressive, I'm still not convinced this was worth the complexity, or even a good idea at all: to me it's based on a false premise –– that the user of a collection usually wants collection transformation operations to result in the same type as the original collection.
In my personal experience however, the **_usage_** I make of the transformed collection is almost always what dictates what I want the end result type to be. If I'm going to test existence I want to transform into a `Set`; if I want random access, into a `IndexedSeq`; if I want mapping, into a `Map`; if I want List-like analysis, into a `LinearSeq`, etc., etc. It rarely (if ever) seems to be the case that I want the data source to retain its original collection type (which is usually irrelevant and merely incidental).

This means I'm usually just writing `xs.iterator ... .toX` or `xs.view ... .toY` (or I should be, if I'm concerned with performance). Does anyone have examples to contradict this impression?

**Comment by julienrf** [comment]
Oh you’re right, `CanBuild[-A, +Repr]` is equivalent to an alias to `() => Builder[A, Repr]`, so there would be no difference… I will try to think of a nice solution for the kind polymorphism issue.

**Comment by dlwh** [comment]
@julienrf ok thanks, I'm a bit less worried, though still somewhat sad.

@LPTK I definitely can see the logic that the old system's complexity may be too much to justify the flexibility it gives you. And I also agree that . Especially now that views are getting improved. 

I do still think it's bad there's now an "abstraction penalty" in terms of preciseness of types: if you have an expression like (just a random thing, not a real thing I find myself doing):

```
x.map(_.swap).flatMap { case (k, vs) => vs.map(k -> _)}
```

that you see repeated in a few places, sometimes with Seq, sometimes with Set, sometimes with Map, you can't extract a single method that abstracts it and preserves the old result types, because overload resolution doesn't preserve across generic boundaries without type classes. (I think?)

Similarly with Set/Bitset.

**Comment by nrinaudo** [comment]
@julienrf kind of hijacking this to say that, if you're going to introduce `CanBuild` or a similar mechanism (I'm all for that, it's hugely useful to me), would it be possible to give some thoughts to making it serializable?

This might seem a bit weird, but when working with Apache Spark or similar frameworks, you need all your values to be serializable. With type class and other implicit parameters, it's really easy to find yourself in a situation where your value holds non-serializable data without realising it. Specifically, the current `CanBuildFrom` is not, or not often, serializable, which break a lot of existing libraries (my specific example is kantan.csv, but I'm sure there are other - you'll find hacks to work around this in popular libraries like shapeless).

**Comment by julienrf** [comment]
I’m closing this issue since the use cases given here are now parts of our tests.

**Comment by dlwh** [comment]
thanks! I appreciate it. Great work, btw
