### ISSUE TITLE
Missing overloads in LongMap

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#440]
`map`, `flatMap` have specific overloads in IntMap, but not in LongMap.

IntMap has a `concat` override with a cast (because `IntMap[+T]` extends `MapOps[Int, T, Map, IntMap[T]]`, we cannot pass `IntMap` as `CC` because it only has one type param - right?), but not LongMap

**Comment by lrytz** [comment]
I tried

```
sealed abstract class IntMap[+T] extends Map[Int, T]
  with MapOps[Int, T, ({type L[K, +V] = IntMap[V]})#L, IntMap[T]]
```

but that fails
```
[error] /Users/luc/scala/scala13/target/library/src_managed/main/scala/collection/immutable/IntMap.scala:160: type arguments [scala.collection.immutable.IntMapUtils.Int,T,[K, +V]scala.collection.immutable.IntMap[V],scala.collection.immutable.IntMap[T]] do not conform to trait MapOps's type parameter bounds [K,+V,+CC[X, +Y] <: scala.collection.immutable.MapOps[X, Y, CC, _],+C <: scala.collection.immutable.MapOps[K,V,CC,C]]
[error]   with MapOps[Int, T, ({type L[K, +V] = IntMap[V]})#L, IntMap[T]]
```

**Comment by julienrf** [comment]
The compilation error means that we can not guarantee that we will always be able to return an `IntMap` (some `Map` transformation operation can change the type of key). That’s why we will have to overload the operations:

~~~ scala
def map[V2](f: ((Int, V)) => (Int, V)): IntMap = …
~~~

Here we know that we can return an `IntMap` because the type of keys is unchanged.

**Comment by julienrf** [comment]
I’m happy to live with a cast in `IntMap` or `LongMap`. At one point I’ve tried to abstract over the return type of map operations that preserve the type of keys but that added a *fifth* type parameter to `MapOps` so I reverted.

**Comment by lrytz** [comment]
Ah yes, of course, thanks.

**Comment by julienrf** [comment]
@lrytz Would you mind issuing a PR for that?

**Comment by lrytz** [comment]
Will do

**Comment by lrytz** [comment]
Actually this was fixed by https://github.com/scala/collection-strawman/pull/447, that's why I didn't include it in my integration branch PR (https://github.com/scala/collection-strawman/pull/452)
