### ISSUE TITLE
Make sure HashSet is at least as performant as in the old collections

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#442]
In #439 I’ve added benchmarks comparing the main operations of hashsets. In some cases we are still under the performance level of the old `HashSet`. Also, in some cases `ChamHashSet` is less performant than `HashSet`. We have to investigate more before committing to a default `Set` implementation.

![equals](https://user-images.githubusercontent.com/332812/36034206-9aaa81de-0db3-11e8-87af-a3ba18d32fe9.png)

`ChamHashSet` wins.

![excl](https://user-images.githubusercontent.com/332812/36034207-9ac51526-0db3-11e8-9b43-17653d21d9a5.png)

The new `HashSet` wins.

![incl](https://user-images.githubusercontent.com/332812/36034208-9ae6ddd2-0db3-11e8-8b0f-8dae91c1163d.png)

The old `HashSet` wins!

![intersection](https://user-images.githubusercontent.com/332812/36034210-9b049d22-0db3-11e8-9b62-adce416570d2.png)

New `HashSet` wins (*ex æquo* with the old one).

![subsetof](https://user-images.githubusercontent.com/332812/36034211-9b40658c-0db3-11e8-8564-19d1502f45c5.png)

`ChamHashSet` wins for sets with more than 100 elements.

![union](https://user-images.githubusercontent.com/332812/36034213-9b57cfc4-0db3-11e8-9bf3-a90836c20449.png)

No one wins.

**Comment by SethTisue** [comment]
one specific performance minus is being investigated at https://github.com/scala/scala-dev/issues/525

**Comment by SethTisue** [comment]
I think is considered resolved now? reopen if you disagree  /cc @szeiger @retronym
