### ISSUE TITLE
Provide descriptive names as alternatives to the most commonly used symbolic method names

### ISSUE THREAD

**Issue by mhalttu** [scala/collection-strawman#46]
As outlined in http://docs.scala-lang.org/style/naming-conventions.html the use of symbolic method names should be avoided. 

I suggest implementing descriptive alternatives to the most commonly used symbolic method names used in the Scala Collections API. I understand that this would add more methods to the API, but I strongly believe it would make the API more accessible for people without an extensive functional background.

As an example, `Map` already now provides `updated` method that is almost synonymous to `+`.

Similarly `++` in `Seq` (or its super class) could be called `concat`
As another example `:+` in `Seq` could be called `append`

**Comment by rinfield** [comment]
FYI:

https://www.slideshare.net/Odersky/scala-days-nyc-2016

https://image.slidesharecdn.com/scaladays-nyc-2016-160510135215/95/scala-days-nyc-2016-62-638.jpg?cb=1462901685

**Comment by mhalttu** [comment]
That sounds exactly what I had in mind, and would be extremely helpful!
