### ISSUE TITLE
List extractor accepts Seq parameters

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#460]
~~~ scala
(Vector(1, 2, 3): Seq[Int]) match {
  case Nil     => "empty"
  case x :: xs => "non empty"
}
~~~

This code compiles and fails at runtime with a match error: https://scastie.scala-lang.org/mRhIPpDDTsCP04gava4SFw

The `::` extractor should not accept a `Seq` as parameter, this should be a compile error.

**Comment by szeiger** [comment]
`::` is a case class, not an extractor. But `Seq` is a non-sealed base class so there is no exhaustiveness checking. If anything, this should be a ticket on scala/bug but I doubt we can improve this without lots of false positives. The current behavior is the same as in 2.12.
