### ISSUE TITLE
Enforce consistency between the available operations of IterableOnce and Iterable

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#465]
Currently these collection types don’t have a common super type.

@lrytz suggested that we write some tests that use reflection to check that the operations and type signatures are consistent between them.

**Comment by lrytz** [comment]
Here's a the current diff of Iterable vs Iterator operations: https://gist.github.com/lrytz/39bdb1b25c23e204c3263809534ba6a0/revisions#diff-5b3b7587cc6e69d92ccb282bab852b31

**Comment by lrytz** [comment]
See also https://github.com/scala/collection-strawman/issues/419

**Comment by szeiger** [comment]
This sounds a lot like the `IterableMonoTransforms` we had in earlier iterations of the design.

**Comment by szeiger** [comment]
I had a look at the diff and most of what I saw looks reasonable. `Iterator` does have methods like `dropRight` that would require forcing and caching everything. OTOH, because an `Iterator` represents a single traversal, it has some `Seq`-like features that are missing from `Iterable`.
