### ISSUE TITLE
Promote `to` over `Coll.from`

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#467]
```
warning: method toList in class IterableOnceExtensionMethods is deprecated (since 2.13.0): Use List.from(it) instead of it.toList
```

I think we should recommend using `it.to(List)` instead. The code is much more readable if operations appear in the order that they are performed.

```
List.from(x.map.filter.tata)
x.map.filter.tata.to(List)
```

Stefan says that we might be able to support cross-compiling by providing an implicit conversion from `Factory` to `CanBuildFrom` in the compat library to make the new syntax work in the old collections.

**Comment by julienrf** [comment]
Note that `to(List)` also works with `Iterator` and is [supported by the compat library](https://github.com/scala/scala-collection-compat/blob/19deff556cedfbff4a43b8cfbd0256a110f3c7ee/src/test/scala/CollectionTest.scala#L12-L15) in 2.12 as well.
