### ISSUE TITLE
HashSet should be parametrized on a hashable type class

### ISSUE THREAD

**Issue by larsrh** [scala/collection-strawman#47]
Tree-style collections (`TreeMap`, `TreeSet`) take an instance of `Ordering[A]` as a parameter. This is necessary because there's only universal equality on the JVM, but not universal "less than". The nice "side effect" of that is that I can pass in custom instances when constructing collections.

On the other hand, hash-style collections (`HashMap`, `HashSet`) _do not_ take an instance of `Hash[A]` as a parameter, for I believe two reasons:

1. there is universal equality and hashing on the JVM
2. the type class doesn't exist yet

If I want to use a different hash code implementation, I can either implement a new collection type or use awkward `newtype`-style wrappers. If the collections were parametrized on a `Hash` instance, I could pass in a custom instance.

Note that this proposal is unaffected by global instance uniqueness. I'm merely suggesting establishing feature parity between hash-style and tree-style collections. Whether or not you should pass in multiple different instances per type is an entirely different discussion.

**Comment by Ichoran** [comment]
@larsrh - Hash must be consistent with equals for hash sets (and maps) to work.  Do you mean for `Hash[A]` to extend `Equals[A]`?

**Comment by larsrh** [comment]
Yes, that's the plan; this would be nicely consistent with `Ordering` which also extends from `Equiv`.

**Comment by larsrh** [comment]
I have been informed that Rust does it in a [similar](https://doc.rust-lang.org/std/collections/struct.HashMap.html) [way](https://doc.rust-lang.org/std/hash/). (As does Haskell, of course.)

**Comment by Ichoran** [comment]
Keep in mind that Rust has essentially zero-cost `newtype` (usually _exactly_ zero-cost) which Scala does not have, so even though Scala can match pretty much any type-level logic (save lifetime) from Rust, it isn't necessarily a good idea for an application area where the primary complaint over the years has been "it's not as fast as Java's HashMap".  So *if* we were to do this we'd have to benchmark very carefully.  One of the biggest arguments in favor would be if we could do an end-run around the logic in generic equals and actually speed things up (despite the extra layer of indirection from the typeclass).

**Comment by julienrf** [comment]
Should we also take advantage of this typeclass to implement `contains` in all the collections (the current implementation relies on universal equality)?

**Comment by odersky** [comment]
Tree-style collections are much less pleasant to use because of the typeclass requirement. That's why there are rarely used compared to hash-based collections. I am very much in favor of looking into a new map type that is parameterized with  hashes and equals. But that should be an add-on, standard collection types will need to continue to use universal equality and hashing.

**Comment by julienrf** [comment]
@odersky You mean that we should keeep `HashMap` the same and create a new `EqMap` type?

**Comment by odersky** [comment]
Yes, exactly.

**Comment by TomasMikula** [comment]
FYI, I previously ported `HashSet`/`HashMap` from  the Scala standard library to the typeclass approach: [TomasMikula/hasheq](https://github.com/TomasMikula/hasheq).

**Comment by TomasMikula** [comment]
I agree that typeclass-based hash collections should be separate from the current universal `hashCode`-based ones, but it would be nice if the implementation could be shared (which is not the case for [hasheq](https://github.com/TomasMikula/hasheq), where the implementation is copy-pasted and adjusted).

**Comment by SethTisue** [comment]
this isn't going to happen for 2.13. closing the ticket since we are (gradually) shutting this repo down, but perhaps the idea still has a future.
