### ISSUE TITLE
Counting in collections

### ISSUE THREAD

**Issue by k0ala** [scala/collection-strawman#472]
I often run up against issues of the following kind. I have a large collection `xs`, and I would like to do one of the following:

1) for each distinct value, get a count of how often it appears in `xs`.
2) more generally, get a count of how often each value `f(x)` appears in `xs.map(f)` (point 1 is a special case with `f` == `identity`).
3) obtain the subset of values in `xs` that occur more than once.
4) more generally, obtain the subset of `xs` for which `f(x)` occurs more than once (point 3 is a special case with `f` == `identity`).

I know that these can all be achieved using `groupBy`, however that seems quite wasteful, because it can potentially build as many new collections as there are elements in `xs`... and counting seems like a common enough use case to warrant some specific methods.

I was thinking of adding something like the following to collection `Coll[A]`:
```
def countByValue: Map[A, Int]             // point 1
def countBy[B](f: A => B): Map[B, Int]    // point 2
def duplicates: Coll[A]                   // point 3
def duplicatesBy[B](f: A => B): Coll[A]   // point 4
```

Is there any interest in this, and if yes, any pointers on where to begin? Presumably it could be written in terms of `aggregate`, but that may be inefficient?

Apache Spark has some functions like this on its RDD collections, see e.g. [countByValue](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.rdd.RDD@countByValue()(implicitord:Ordering[T]):scala.collection.Map[T,Long]) or [countByKey](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.rdd.PairRDDFunctions@countByKey():scala.collection.Map[K,Long]). There are also some useful approximate algorithms in addition to exact counts.

**Comment by julienrf** [comment]
I think [groupMapReduce](https://static.javadoc.io/ch.epfl.scala/collection-strawman_2.13.0-M2/0.9.0/strawman/collection/Iterable.html#groupMapReduce[K,B](key:A=%3EK)(f:A=%3EB)(reduce:(B,B)=%3EB):strawman.collection.immutable.Map[K,B]) supports all these use cases without creating extra collections.

**Comment by k0ala** [comment]
@julienrf Thanks, I will look into `groupMapReduce`, perhaps these methods can be implemented efficiently with it. What do you think about adding these methods to the general collections API?

**Comment by julienrf** [comment]
We already have a lot of methods, it’s preferable to introduce as few new methods as possible :) I think `groupMap` and `groupMapReduce` are general enough to support your use case.
