### ISSUE TITLE
Consider dropping `filterInPlace`, `mapInPlace`, and `flatMapInPlace` from unordered mutable collections

### ISSUE THREAD

**Issue by Ichoran** [scala/collection-strawman#473]
The presence of a method like `filterInPlace` suggests that one might at some point want to use it.  Unfortunately, unordered collections can't efficiently `filterInPlace` via a general algorithm; it works out to being something like

```
val temp = xs.toArray.filterInPlace(p)
xs.clear
xs ++= temp
```

which is not very helpful.  Sequentially dropping every element as you find it is a no-go; there is no promise that later elements will actually still be iterable-to, and it might have O(n^2) performance to drop an element at a time.  There are various relatively straightforward algorithms for array-based or linked-list-based ordered collections that do perform well enough (one pass through, moving all retained elements).

There is a similar but worse problem with `mapInPlace`, where in unordered collections you can't even put the new element in the collection because you might (incorrectly) remove it again as you iterate through.  `flatMapInPlace` has a similar conundrum.

I recommend that we remove these methods where there is no natural implementation.

**Comment by szeiger** [comment]
We should consider `mapValuesInPlace` which can be implemented efficiently.

**Comment by szeiger** [comment]
Discussed with @julienrf and @lrytz today and we agree with deprecating these methods. But they're actually new, right? In this case we should remove them immediately.

**Comment by Ichoran** [comment]
Yes, they're new.  Everything `InPlace` is new.  If these are to go, and I think they should, we can just delete them.

`mapValuesInPlace` should stay (or be created--I forget if it's there).
