### ISSUE TITLE
Fix unbound references in API documentation

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#510]
- [ ] `IterableOnceOps` (introduced in #480) produces a lot of documentation errors. We should check that the documentation variables are always defined before they are used,
- [ ] Also, now `Iterable` inherits from a lot of comments that are relevant to `IterableOnce` only (about the fact that an operation consumes the collection or not). We should override these comments (or redefine the variables they use).

**Comment by szeiger** [comment]
Unassigning myself for now because I haven't gotten around to starting this.

**Comment by chrisphelps** [comment]
I'd like to take a look at this one. I should get to it in the next couple of days.
