### ISSUE TITLE
immutable.{HashMap, ChampHashMap} should use a serialization proxy

### ISSUE THREAD

**Issue by retronym** [scala/collection-strawman#524]
See also #523, which seeks to define a general strategy for serialization 

HashMaps need to customize deserialization because element hash codes could be different on the deserizalizing JVM. `immutable.HashMap` has [this in 2.13.x](https://github.com/scala/scala/blob/9291e12004d6c96121467b1468249cb04afede2e/src/library/scala/collection/immutable/HashMap.scala#L102), but it hasn't been ported into this repo in either of the immutable hashmap implementations.

**Comment by lrytz** [comment]
There's an old (fixed) ticket for this: https://github.com/scala/bug/issues/1600. I disabled the test case for now. Once this is fixed, `test/files/jvm/t1600.scala` needs to be re-enabled (marked with `TODO-newColl`).
