### ISSUE TITLE
Cover all the cases that have been removed from enrich-gentraversable.scala

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#535]
See https://github.com/scala/scala/pull/6488, which removes the test for array enrichment.

We should add to collections-contrib a test that covers these use cases.

Also, maybe we should move the enrichment machinery to the core instead of leaving it in collections-contrib?

**Comment by lrytz** [comment]
> Maybe we should move the enrichment machinery to the core instead of leaving it in collections-contrib?

+1

I think it's important to ship 2.13 with clear instructions (and helpers) how to write extension methods of various levels of genericity.
