### ISSUE TITLE
Iterable.copyToBuffer no longer exists

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#538]
It's easy enough to write `buf ++= iterable`, but we should probably deprecate the method first.

**Comment by julienrf** [comment]
Note that the rewrite rule [already exists](https://github.com/scala/collection-strawman/blob/master/scalafix/2.13/rules/src/main/scala/fix/Collectionstrawman_v0.scala#L89-L97), but I agree that we should deprecate the method.
