### ISSUE TITLE
collection.Set no longer has a varargs + method

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#540]
https://github.com/scala/collection-strawman/commit/87b27654d4a5bc811ec957114316f8c596733ec1 added a deprecated `+` method to `collection.Set` (also suggested in https://github.com/scala/collection-strawman/issues/375), but only a version taking a single parameter. In 2.12 there's an overload with varags, allowing `s + (1, 2, 3)`. Should we add that (deprecated) overload?

**Comment by lrytz** [comment]
(ant for collection.Map)

**Comment by szeiger** [comment]
Also see https://github.com/lampepfl/dotty/pull/4311. We shouldn't use varargs for symbolic operators going forward but it's OK for deprecated methods.
