### ISSUE TITLE
StreamView no longer exists

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#543]
In 2.12 there's `StreamView`, which allows things like
```
scala> Stream.from(0).view.flatMap(n => List(n, n * 2)).force.take(6).toList
res4: List[Int] = List(0, 0, 1, 2, 2, 4)
```

We need to decide if we need to continue supporting this, or if it's just something for the release notes.

https://github.com/scala/bug/issues/3511

In scala/scala, I removed the `test/files/run/t3511.scala` test case. It should be restored (from 2.12.x) if we bring back `StreamView`.

**Comment by szeiger** [comment]
`force` is deprecated, so any changes here would be purely for backwards compatibility. Adding a special `StreamView` type would be a more permanent change. The code can be easily rewritten to `Stream.from(0).view.flatMap(n => List(n, n * 2)).to(Stream).take(6).toList` and you do get a deprecation warning for the version with `force`.
