### ISSUE TITLE
operation `SortedSet#to` has been renamed to `rangeTo`

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#546]
We should have a rewrite rule that fixes existing code bases, and we should mention this incompatibility in the migration notes.

**Comment by Ichoran** [comment]
Which operation `to`?

**Comment by julienrf** [comment]
In `SortedSet`. I’ve updated the issue title.

**Comment by Ichoran** [comment]
Then you should change `from` to `rangeFrom` also, for symmetry.  Or switch to `atMost` and `atLeast`, or something.

**Comment by szeiger** [comment]
Fixed in https://github.com/scala/scala/pull/6537
