### ISSUE TITLE
mutable.Stack.reverse doesn't return a stack

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#547]
2.12:
```
scala> Stack(1,2,3).reverse
res1: scala.collection.mutable.Stack[Int] = Stack(3, 2, 1)
```

2.13
```
scala> Stack(1,2,3).reverse
res12: scala.collection.mutable.ArrayDeque[Int] = ArrayDeque(3, 2, 1)
```

Can the override in `ArrayDeque` be implemented to return a `C`?

Once this is fixed, `test/files/run/t4535.scala` needs an `--update-check`.

Side-question: is there a type checking issue? `SeqOps.reverse` is defined to return `C`, and we have `Stack[A] extends ArrayDeque[A] .. with IndexedSeqOps[A, Stack, Stack[A]] ..`. It seems to me the override of `reverse` inherited from `ArrayDeque` doesn't satisfy the requirement.

**Comment by Ichoran** [comment]
Note also https://github.com/scala/collection-strawman/issues/505

**Comment by julienrf** [comment]
I think this is fixed in https://github.com/scala/scala/pull/6508.
