### ISSUE TITLE
Views are not serializable

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#548]
```
scala> new java.io.ObjectOutputStream(new java.io.ByteArrayOutputStream()).writeObject(Set(1).view)
java.io.NotSerializableException: scala.collection.View$$anon$1
```

Once fixed, re-enable the test in `test/files/run/t5018.scala`.

**Comment by marcelocenerine** [comment]
I brought this up once. See @Ichoran opinion: https://gitter.im/scala/collection-strawman?at=5a7de57e7084124a345909e3

**Comment by SethTisue** [comment]
I think I'm comfortable with not supporting this
