### ISSUE TITLE
Re-add (deprecated?) collection.Seq.updated?

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#549]
Can work around with `collection.Seq(1).patch(0, List(2), 1)`...

Once fixed, revert fix `TODO-newColl` in `test/files/run/t5328.scala`.

**Comment by julienrf** [comment]
@szeiger We eventually pulled the `+:` and `:+` operations of `collection.immutable.Seq` to `collection.Seq`, without deprecating them.
