### ISSUE TITLE
Stream/LazyList.addString should not force

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#550]
In 2.12, stream.addString adds `?` and detects cycles, similar to what `toString` does in the new collections.

Once this is fixed, re-enable tests commented out with `TODO-newColl` in `test/files/run/t8680.scala`.

**Comment by szeiger** [comment]
There's a very unfortunate asymmetry between `mkString` and `addString` due to the way https://github.com/scala/bug/issues/8680 was resolved. It would be nice to come up with a better solution but OTOH we already have more than enough breaking changes.
