### ISSUE TITLE
We need dev-oriented documentation for M4

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#566]
We need to provide developer-oriented documentation for M4 for library maintainers. A go-to document (which can link to other articles) where they can read about the new design, common issues that they might encounter: common changes in user code, common issues with custom collections, tips for cross-building.

https://github.com/scala/collection-strawman/wiki/FAQ

**Comment by julienrf** [comment]
I’ve updated the FAQ, did I forget to mention something? Is it detailed enough?

**Comment by lrytz** [comment]
It looks really good to me. I'll keep it in mind while working on collections things.
