### ISSUE TITLE
Separating interfaces and implementations

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#78]
# Context

`XxxOps` types provide convenient default implementations for most methods. Some of them rely on protected `coll`, `fromIterable` and `fromSpecificIterable` members ([example](https://github.com/scala/collection-strawman/blob/c7b52041058c8aa4fb36376b5f6e9188acd1f4e9/src/main/scala/strawman/collection/Iterable.scala#L156)). Often the `coll` member’s type is refined so that more complex operations can be implemented (see [here](https://github.com/scala/collection-strawman/blob/c7b52041058c8aa4fb36376b5f6e9188acd1f4e9/src/main/scala/strawman/collection/immutable/Set.scala#L17), and [there](https://github.com/scala/collection-strawman/blob/c7b52041058c8aa4fb36376b5f6e9188acd1f4e9/src/main/scala/strawman/collection/immutable/Set.scala#L42-L47)). For convenience, this member is implemented in `Iterable`, as follows:

~~~ scala
def coll: this.type = this
~~~

# Problems

- When we refine the type of `coll` to be `C` or `CC[A]`, we then have to put upper bounds on these `C` and `CC` type parameters. Then these upper bounds show up everywhere and make the code less readable ([example](https://github.com/scala/collection-strawman/blob/c7b52041058c8aa4fb36376b5f6e9188acd1f4e9/src/main/scala/strawman/collection/immutable/SortedSet.scala#L14-L16)) ;
- The signature of `fromIterable` and `fromSpecificIterable` is impossible to implement for specialized `View`s (like `IndexedView`). See [this comment](https://github.com/scala/collection-strawman/pull/76#issuecomment-299475201) for more details. A derived consequence of this is that transformation operations on `IndexedView` return a `View` unless they are explicitly overriden ([example](https://github.com/scala/collection-strawman/blob/c7b52041058c8aa4fb36376b5f6e9188acd1f4e9/src/main/scala/strawman/collection/View.scala#L170-L175)).

# Proposal

- Having traits with no implemented methods would make it possible to remove the bounds on the type parameters. (But that might just delay the problem because if we want to have reusable implementations inherited by concrete collections then those reusable implementations will have the bounds)
- I think that another consequence will be that Java collection’s decorators and Views will be better integrated (e.g. it will be possible to make `IndexedView[A]` extend `Seq[A]`, and it will be simpler to specialize its operations’ return type to `IndexedView[A]`).

I’m thinking of giving a try to this idea. But before I start, do you have any comment?

**Comment by szeiger** [comment]
`IndexedView` should not extend `Seq`. IMHO Views should be entirely separate from Seqs, Sets and Maps as a basic collection type (i.e. the level at which universal equality can be defined in a useful way). The problem in the other PR was not that it's unsound to do so with the current design but that it tried to do it at all.

**Comment by julienrf** [comment]
Thanks for this clarification, I agree that it would be a mistake to make views extend `Seq`.

On the other hand, that would be nice if operations expecting indexed collections could be used with indexed views, wdyt?

**Comment by szeiger** [comment]
It depends on the available operations. Currently `IndexedSeq` doesn't give you any additional operations over `Seq`. We may want to ask instead if it makes sense to define an operation that can accept either a `Seq` or a `View`. But given that a `View` of a `Seq` is the same as a `View` of a non-`Seq`, I'm inclined to say no. If you can operate on a `Set`, for example, just as well as on a `Seq`, you ask for an `Iterable`, which also allows the use of a `View`. If a `Set` is not acceptable, a `View` based on a `Set` shouldn't be acceptable, either.

**Comment by julienrf** [comment]
Closed by #174.
