### ISSUE TITLE
Regression in SortedMap

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#81]
I commented directly on the commit that introduced the regression but I think it’s easier to keep track of the issue if I create a proper issue…

I didn’t notice that when I first reviewed the code but I think there is a regression [here](https://github.com/scala/collection-strawman/blob/dfe1aad1ae7c05bae325e8a848c51e99dc1c1a76/src/main/scala/strawman/collection/immutable/SortedMap.scala#L16).

The `updated` and `+` methods are overriden in order to refine the return type `CC` so that it is `SortedMap` instead of `Map` (which we would have otherwise, because we inherit `MapLike[K, V, Map]`).

This is a problem because that means that we will have to carefully refine the return type of all the operations inherited from `Map`, furthermore the operator aliases can not be made `final` anymore.

I initially fixed this problem in #56 by introducing (yet…) another abstraction named `MapValuePolyTransforms`, whose purpose was to model the return type of transformation operations that return a `Map` collection with the same key type but a different value type (like this `updated` method).

To adapt this solution to the new design, we would have to introduce a **fifth** type parameter to the `MapOps` trait:

~~~ scala
trait MapOps[K, +V, +CC[X, Y], +VC[Y], +C] {
  def updated[V0 >: V](key: K, value: V0): VC[V0]
}
~~~

Where `VC` means “*constructor* for a map with a different type of *values*”.

In practice this is how the `Map` trait would instantiate these type parameters:

~~~ scala
trait Map[K, +V] extends MapOps[K, V, Map, [V0] => Map[K, V0], Map[K, V]]
~~~

As you can see, one problem is that we have no support for partial type application (I wish I could replace `[V0] => Map[K, V0]` with just `Map[K, _]`), and, furthermore, in Scala we don’t have type lambdas, which means that we would have to define something like this:

~~~ scala
trait PartialAp[TC2[X, Y], A] {
  type TC[B] = TC2[A, B]
}
~~~

And then:

~~~ scala
trait Map[K, +V] extends MapOps[K, V, Map, PartialAp[Map, K]#TC, Map[K, V]]
~~~

Any thoughts, @odersky, @Ichoran, @DarkDimius, @szeiger?

I’m thinking of an alternative design that would not have all these type parameters, and, consequently, that would not hit these issues… (but it will have other trade offs…)

**Comment by odersky** [comment]
My position is, `SortedMap` is really tricky because it pushes the envelope. We need to accept that `SortedMap` has a messy implementation. If it has to override a bunch of methods from `Map`, so be it.  But it's better than having complex, unintuitive abstractions leak out into the rest of the framework.

Also, keep in mind that the _worst_ that could happen if we forget an override is that some `SortedMap` operation returns a `Map` instead of `SortedMap`. That might be inconvenient but it's not fatal (contrast with the previous situation with views where forgetting an override made the operation strict, that was much more problematic).

**Comment by odersky** [comment]
> This is a problem because that means that we will have to carefully refine the return type of all the operations inherited from Map

You mean, all monotransforms, right? The rest should not be a problem.

**Comment by julienrf** [comment]
> Which operations specifically need to be overridden?

All operations that return a map with the same type of keys but a different type of values. I call these operations “polymorphic on the Map values only”: `concat`, `updated` and `mapValues` (I’m not sure we’ll have other such operations).
