### ISSUE TITLE
Migration tool to switch from the current collections to the strawman

### ISSUE THREAD

**Issue by julienrf** [scala/collection-strawman#99]
In order to make it easier for users to try the strawman we should provide a tool that replaces references to the current collections with references to the strawman.

**Comment by julienrf** [comment]
Corner case: `1 to 10` should produce a `strawman.collection.immutable.Range`.

**Comment by ShaneDelmore** [comment]
What exactly is the issue?  I think scalafix can handle this fairly easily but am not sure I am understanding what the problem is.

**Comment by julienrf** [comment]
I’m sorry the issue description lacks details. Let me add some details: to move a code base to the strawman, a rule of thumb is just to import collection types from the `strawman.collection` namespace instead of `scala.collection`. However, there are some corner cases:
- some aliases are `scala` or `scala.Predef` namespaces ;
- implicit conversions enriching `Array`s and providing `Range` syntax are in `scala.Predef` too. I think that we will have to *un*import the implicits that are in `Predef` and to import those that are (currently) in `strawman.collection`.

**Comment by olafurpg** [comment]
Can you provide some example diffs @julienrf ? It should be possible to implement some of these with Scalafix.

**Comment by julienrf** [comment]
- When a “default” collection is used (e.g. `List`) we should unimport it from the `scala` package and import it from `strawman.collection`:

~~~ diff
+ import scala.{List => _}
+ import strawman.collection.immutable.List
List(1, 2, 3)
~~~

~~~ diff
+ import scala.{Nil => _}
+ import strawman.collection.immutable.Nil
1 :: 2 :: 3 :: Nil
~~~

- When a collection whose type is not aliased in the `scala` package is used, we should replace its import with one that points to `strawman.collection`:

~~~ diff
- import scala.collection.mutable.ArrayBuffer
+ import strawman.collection.mutable.ArrayBuffer
~~~

- When the `Range` syntax is used we should replace it with the one from the strawman:

~~~ diff
+ import scala.Predef.{intWrapper => _}
+ import strawman.collection.intWrapper
1 to 10
~~~

(maybe it is enough to just import the new implicit conversion. I don’t know if there will be an ambiguity if don’t unimport the one in `Predef`)

- When collection operations are used with `String` and `Array` values, we should replace the decorators with the one from the strawman:

~~~ diff
+ import scala.Predef.{augmentString => _}
+ import strawman.collection.stringToStringOps
"foo" ++ "bar"
~~~

~~~ diff
+ import scala.Predef.{intArrayOps => _}
+ import strawman.collection.arrayToArrayOps
Array(1, 2, 3) map (_ + 1)
~~~
